### PR TITLE
PDF and Video Thumbnails

### PR DESCRIPTION
**Pull request by dannylamb**
**Do not merge! Used for testing the related PRs.**

Part of https://github.com/Islandora-CLAW/CLAW/issues/1111
Resolves https://github.com/Islandora-CLAW/CLAW/issues/1005

Deploys
- https://github.com/Islandora-CLAW/islandora_demo/pull/28
- https://github.com/Islandora-CLAW/islandora/pull/130
- https://github.com/Islandora-Devops/ansible-role-crayfish/pull/22
- https://github.com/Islandora-CLAW/Crayfish/pull/63

## Testing instructions

- Delete your `roles/external` directory
- Pull in this PR
- `vagrant up`
- Make a repository item, give it a model of Video, and give it an original file.  After a while you'll see two derivatives made
  - An mp4 service file (which is what takes a while...)
  - A jpeg thumbnail, which is the first frame of the video (needs image styles to get down to size)
- Make a repository item, give it a model of Digital Document (new as of this work), and give it a pdf as an original file.  Pretty quickly you'll see two derivatives made
  - A jpeg service file, which is the first page of the pdf
  - A jpeg thumbnail of the first page of the pdf (no image styles needed)

### CODE REVIEW

**Comment by dannylamb** [comment]
@Islandora-Devops/committers This is ready to test!

**Comment by seth-shaw-unlv** [comment]
Everything works as advertised. However, is there an option to have the video thumbnails be smaller? Currently the thumbnails keep the same resolution as the original video.

**Comment by Natkeeran** [comment]
@dannylamb 

The file name of the pdf is called Service File instead of Thumbnail.  

Also, probably not related, trying to create another pdf file, throws this error:

```

Message | User warning:  cURL error 7: Failed to connect to localhost port 8080: Connection  refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in Twistor\FlysystemStreamWrapper->triggerError() (line 932 of /var/www/html/drupal/vendor/twistor/flysystem-stream-wrapper/src/FlysystemStreamWrapper.php)  #0 /var/www/html/drupal/web/core/includes/bootstrap.inc(584):  _drupal_error_handler_real(512, 'cURL error 7: F...',  '/var/www/html/d...', 932, Array) #1 [internal function]: _drupal_error_handler(512, 'cURL error 7: F...',  '/var/www/html/d...', 932, Array) #2  /var/www/html/drupal/vendor/twistor/flysystem-stream-wrapper/src/FlysystemStreamWrapper.php(932):  trigger_error('cURL error 7: F...', 512) #3  /var/www/html/drupal/vendor/twistor/flysystem-stream-wrapper/src/FlysystemStreamWrapper.php(709):  Twistor\FlysystemStreamWrapper->triggerError('stat',  Object(GuzzleHttp\Exception\ConnectException)) #4 [internal function]:  Twistor\FlysystemStreamWrapper->url_stat('fedora://2019-0...', 2) #5 /var/www/html/drupal/web/core/includes/file.inc(299):  is_dir('fedora://2019-0...') #6 /var/www/html/drupal/web/core/modules/file/file.module(1363):  file_prepare_directory('fedora://2019-0...', 1) #7  /var/www/html/drupal/web/core/modules/file/src/Element/ManagedFile.php(74):  file_managed_file_save_upload(Array,  Object(Drupal\Core\Form\FormState)) #8  /var/www/html/drupal/web/core/modules/file/src/Plugin/Field/FieldWidget/FileWidget.php(324):  Drupal\file\Element\ManagedFile::valueCallback(Array, Array,  Object(Drupal\Core\Form\FormState)) #9 [internal function]:  Drupal\file\Plugin\Field\FieldWidget\FileWidget::value(Array, Array,  Object(Drupal\Core\Form\FormState)) #10  /var/www/html/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(1254):  call_user_func_array(Array, Array) #11  /var/www/html/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(990):   Drupal\Core\Form\FormBuilder->handleInputElement('media_file_add_...',  Array, Object(Drupal\Core\Form\FormState)) #12  /var/www/html/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(1060):  Drupal\Core\Form\FormBuilder->doBuildForm('media_file_add_...',  Array, Object(Drupal\Core\Form\FormState)) #13  /var/www/html/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(1060):  Drupal\Core\Form\FormBuilder->doBuildForm('media_file_add_...',  Array, Object(Drupal\Core\Form\FormState)) #14  /var/www/html/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(1060):  Drupal\Core\Form\FormBuilder->doBuildForm('media_file_add_...',  Array, Object(Drupal\Core\Form\FormState)) #15  /var/www/html/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(561):  Drupal\Core\Form\FormBuilder->doBuildForm('media_file_add_...',  Array, Object(Drupal\Core\Form\FormState)) #16  /var/www/html/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(318):  Drupal\Core\Form\FormBuilder->processForm('media_file_add_...',  Array, Object(Drupal\Core\Form\FormState)) #17  /var/www/html/drupal/web/core/lib/Drupal/Core/Controller/FormController.php(93):  Drupal\Core\Form\FormBuilder->buildForm('media_file_add_...',  Object(Drupal\Core\Form\FormState)) #18 [internal function]:  Drupal\Core\Controller\FormController->getContentResult(Object(Symfony\Component\HttpFoundation\Request),  Object(Drupal\Core\Routing\RouteMatch)) #19  /var/www/html/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123):  call_user_func_array(Array, Array) #20  /var/www/html/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(582):  Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #21  /var/www/html/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124):   Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext),  Object(Closure)) #22  /var/www/html/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97):   Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array,  Array) #23 /var/www/html/drupal/vendor/symfony/http-kernel/HttpKernel.php(151):   Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #24 /var/www/html/drupal/vendor/symfony/http-kernel/HttpKernel.php(68):  Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request),  1) #25  /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57):   Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request),  1, true) #26  /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47):   Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request),  1, true) #27  /var/www/html/drupal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(99):   Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request),  1, true) #28  /var/www/html/drupal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(78):   Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request),  1, true) #29  /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47):   Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request),  1, true) #30  /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52):   Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request),  1, true) #31  /var/www/html/drupal/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23):   Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request),  1, true) #32 /var/www/html/drupal/web/core/lib/Drupal/Core/DrupalKernel.php(693):   Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request),  1, true) #33 /var/www/html/drupal/web/index.php(19):  Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #34 {main}.
-- | --
```

**Comment by seth-shaw-unlv** [comment]
@Natkeeran it looks like your tomcat is down.

**Comment by seth-shaw-unlv** [comment]
> However, is there an option to have the video thumbnails be smaller? Currently the thumbnails keep the same resolution as the original video.

See [this comment](https://github.com/Islandora-CLAW/islandora_demo/pull/28#discussion_r283004498) for a suggested solution.

**Comment by Natkeeran** [comment]
@seth-shaw-unlv 
Do those settings bring down the tomcat?

**Comment by Natkeeran** [comment]
Yes, restarting Tomcat makes it work.  

I am wondering how I ended up in that situation and how pdf got a TN as a Service file!

**Comment by seth-shaw-unlv** [comment]
I'm not sure what is going on, @Natkeeran. I can confirm that the PDF I uploaded worked properly:
Screen Shot 2019-05-10 at 1 16 28 PM

Although, why are we generating a Jpeg of the PDF's first page for a service file? Shouldn't we rather just use the PDFjs display?

**Comment by dannylamb** [comment]
@seth-shaw-unlv It's a straight up 7.x-ism that i'm replicating.  We have a PREVIEW datastream that's the first page.  It's not really required per se.  Folks migrating from 7.x will automagically get one if they use our migration tooling, and for greenfields I see how this is probably unnecessary.  I'm fine with removing that as a default, especially considering how easy it is to do if you have the use case for a larger picture of a page from the pdf.

**Comment by dannylamb** [comment]
I removed the service file action from the context reaction in islandora_demo.

**Comment by dannylamb** [comment]
@seth-shaw-unlv PR is updated and good to go now that everything else has been merged in.

**Pull request merged**
