### PR TITLE
d9 build

### PR DESCRIPTION
**Pull request by elizoller**
**GitHub Issue**: (https://github.com/Islandora/documentation/issues/1730)

# What does this Pull Request do?

Changes the playbook to build a d9 drupal site

# What's new?
remove carapace stuff
install temp branches of d9 code + dependencies

# How should this be tested?
run vagrant up

# Additional Notes:
~~1. composer is not happy about the minimum stability so the first time it runs, i go in and manually change the minimum-stability from "stable" to "dev" in `/var/www/html/drupal/composer.json` and then run `vagrant provision` to continue the build.
previously it was dying on the `Run migration` step in the post-install.yml but some minor config changes for islandora and islandora_defaults resolved that.~~
i **think** we don't need to adjust the minimum stability anymore, it should work out of the box

i ran this on an ubuntu/bionic64 base box version `20200121.0.0` and it appears to have given me php 7.4.13 out of the box

# Interested parties
@Islandora-Devops/committers

### CODE REVIEW

**Comment by elizoller** [comment]
note that changes to the Vagrantfile should only persist for this PR and should be returned to their previous values before merging.

**Comment by seth-shaw-unlv** [comment]
@elizoller, can we get the branch conflict resolved?

**Comment by elizoller** [comment]
@seth-shaw-unlv ok should be set

**Comment by seth-shaw-unlv** [comment]
Currently spinning this up and it spit out the following:

```
TASK [geerlingguy.drupal : Install dependencies with composer require (this may take a while).] ***
Tuesday 12 January 2021  21:05:48 -0800 (0:00:01.167)       0:07:03.317 ******* 
changed: [default] => (item=zaporylie/composer-drupal-optimizations:^1.1)
changed: [default] => (item=drupal/devel:^4.0)
changed: [default] => (item=drupal/core-dev)
failed: [default] (item=phpspec/prophecy-phpunit:^2) => {"ansible_loop_var": "item", "changed": false, "item": "phpspec/prophecy-phpunit:^2", "msg": "./composer.json has been updated Running composer update phpspec/prophecy-phpunit Loading composer repositories with package information Updating dependencies Your requirements could not be resolved to an installable set of packages. Problem 1 - phpspec/prophecy-phpunit[dev-master, v2.0.0, ..., v2.0.1] require phpunit/phpunit ^9.1 -> found phpunit/phpunit[9.1.0, ..., 9.5.x-dev] but the package is fixed to 8.5.13 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command. - phpspec/prophecy-phpunit 2.0.x-dev is an alias of phpspec/prophecy-phpunit dev-master and thus requires it to be installed too. - Root composer.json requires phpspec/prophecy-phpunit ^2 -> satisfiable by phpspec/prophecy-phpunit[v2.0.0, v2.0.1, 2.0.x-dev (alias of dev-master)]. Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions. Installation failed, reverting ./composer.json and ./composer.lock to their original content.", "stdout": "./composer.json has been updated\nRunning composer update phpspec/prophecy-phpunit\nLoading composer repositories with package information\nUpdating dependencies\nYour requirements could not be resolved to an installable set of packages.\n\n  Problem 1\n    - phpspec/prophecy-phpunit[dev-master, v2.0.0, ..., v2.0.1] require phpunit/phpunit ^9.1 -> found phpunit/phpunit[9.1.0, ..., 9.5.x-dev] but the package is fixed to 8.5.13 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.\n    - phpspec/prophecy-phpunit 2.0.x-dev is an alias of phpspec/prophecy-phpunit dev-master and thus requires it to be installed too.\n    - Root composer.json requires phpspec/prophecy-phpunit ^2 -> satisfiable by phpspec/prophecy-phpunit[v2.0.0, v2.0.1, 2.0.x-dev (alias of dev-master)].\n\nUse the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.\n\nInstallation failed, reverting ./composer.json and ./composer.lock to their original content.\n", "stdout_lines": ["./composer.json has been updated", "Running composer update phpspec/prophecy-phpunit", "Loading composer repositories with package information", "Updating dependencies", "Your requirements could not be resolved to an installable set of packages.", "", "  Problem 1", "    - phpspec/prophecy-phpunit[dev-master, v2.0.0, ..., v2.0.1] require phpunit/phpunit ^9.1 -> found phpunit/phpunit[9.1.0, ..., 9.5.x-dev] but the package is fixed to 8.5.13 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.", "    - phpspec/prophecy-phpunit 2.0.x-dev is an alias of phpspec/prophecy-phpunit dev-master and thus requires it to be installed too.", "    - Root composer.json requires phpspec/prophecy-phpunit ^2 -> satisfiable by phpspec/prophecy-phpunit[v2.0.0, v2.0.1, 2.0.x-dev (alias of dev-master)].", "", "Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.", "", "Installation failed, reverting ./composer.json and ./composer.lock to their original content."]}
```

So, there is an issue with the lock file?

**Comment by seth-shaw-unlv** [comment]
Still building, but that got me past composer, so 🤞.

**Comment by elizoller** [comment]
i'm suspecting something still isn't quite right because there was a lot to update when i went in and can composer update

**Comment by seth-shaw-unlv** [comment]
This works as advertised, but we will want to remove items instead of just commenting them out. Also, I presume we want to change the default image back to the islandora/8 one and drop "D9 Build" from the VM's name.

**Comment by elizoller** [comment]
will we roll a new version of that base box?

**Comment by seth-shaw-unlv** [comment]
I don't suppose @dannylamb will until we cut a new release. The base box is targeted to the most recent release for those who want to get an introduction, not for those of us playing on the razor's edge.

**Comment by seth-shaw-unlv** [comment]
Looks good. I'll spin it up a final time tonight or tomorrow before merging.

**Review by seth-shaw-unlv — APPROVED** [review]
🚀

**Pull request merged**
