### PR TITLE
No Ubuntu Required

### PR DESCRIPTION
**Pull request by whikloj**
* Remove dependency on ubuntu user
* Fix Ubuntu bootstrap

https://www.youtube.com/watch?v=r0qBaBb1Y-U

### CODE REVIEW

**Comment by MarcusBarnes** [comment]
Appears to build successfully.  The Islandora namespace in Blazegraph was not selected by default, but this may not related to the changes in this pull-request.  

@whikloj Any other things I should check for when testing and reviewing this pull-request?  Thank you in advance.

**Comment by whikloj** [comment]
Not really, this was just to ensure that the system worked without relying on the `/home/ubuntu` directory.

**Comment by dannylamb** [comment]
@MarcusBarnes Turns out setting that default namespace for the web UI is a bit of an ordeal: https://github.com/Islandora-CLAW/CLAW/issues/536

We settled on adding documentation around it in https://github.com/Islandora-CLAW/claw_vagrant/pull/54

It's probably worth adding that to claw-playbook documentation as well.

**Comment by MarcusBarnes** [comment]
@dannylamb Thanks for the clarification.

**Comment by whikloj** [comment]
Oh 🤦‍♂️  I was thinking of @Natkeeran's work to add the islandora namespace...I wasn't thinking about it being auto-selected in Blazegraph. Yeah @MarcusBarnes that seems to be a browser/cookies thing and not easy to affect.

**Pull request merged**
