### PR TITLE
Paged content config

### PR DESCRIPTION
**Pull request by dannylamb**
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/932

# What does this Pull Request do?

This pulls together all the config needed for the work from the Paged Content sprint.  It ties together all the great work from everyone.  Plus it installs a few extra things we've collected over time but aren't installed by default (oai-pmh and breadcrumbs).  Also: `admin_toolbar`.

# What's new?
Paged content!

# How should this be tested?

- Pull down this PR
- `vagrant up`
- Make a 'Repository Item' and give it a model of 'Paged Content'
- Add some children to it
  - Give each one a model of 'Page'
  - Give each one a TIFF or JPEG for an 'Original File'
- Clear your cache
- Visit the 'Paged Content' item and you should see openseadragon pop up with arrows to go left/right through the pages.  You should also see a 'reference strip' at the bottom of the viewer so you can see all the pages and where you are in the sequence.
- From your 'Paged Content' node, click its Children tab, and then the "Reorder Children" button
- Re-order the pages using the drag and drop
- Clear your cache
- Visit your 'Paged Content' node again, and the order of the pages should be reflected.

# Interested parties
Fun one to test that shows all the great work the community has done!  @Islandora-Devops/committers @rangel35 @dbernstein @elizoller @manez

### CODE REVIEW

**Comment by DonRichards** [comment]
What's the story with JP2 support?

**Comment by dannylamb** [comment]
It would work the same way as a tiff.  If you already have JP2s you're already fine (try one though, please!).  If you need to generate them, I think we're hung up on reliably generating them.  But its been a while since we've investigated that.

**Comment by rangel35** [comment]
@dannylamb great, we are generating the JP2s already so I can test that tomorrow

**Comment by rangel35** [comment]
@dannylamb @DonRichards I tested this with ingested JP2s and it worked as advertised...so if you have JP2s pre-created then you can use them...

**Comment by rangel35** [comment]
any chance the thumbnail panel at the bottom could be made smaller....

**Comment by dannylamb** [comment]
@rangel35 Yep.  In Configuration > Media > Openseadragon settings, there's a slew of options to play with.

Screenshot from 2019-09-27 07-49-52

**Comment by rangel35** [comment]
is there a way to add page level metadata to the display...currently only the top book level metadata shows up for every page but if the individual children also contain metadata that is lost (not displayed)

**Comment by dannylamb** [comment]
Off the top of my head I don't know.  If you can put it in the manifest, and i can pass it to the viewer, then in theory it's possible.

**Comment by dannylamb** [comment]
FYI I've noticed that when viewing individual pages with openseadragon, there's some issues.  Sequence mode when there's only one item really messes with things.  I'll see if I can make the viewer autodetect if they need to go into sequence mode.

**Comment by seth-shaw-unlv** [comment]
@rangel35, I mentioned that to @dannylamb on a thread in Slack. OpenSeadragon does support [overlays](https://openseadragon.github.io/examples/ui-overlays/) that can add metadata (see the "Overlaying Complex HTML" example in the linked page); although the provided example didn't persist across the sequence paging. I'm sure we could do it, but not in time for IslandoraCon or even 1.1 unless someone got cracking on it now. 

Brainstorming here: we would have to add a relationship between the media at it's node in the IIIF Manifest view to get the fields we want to display and then update the IIIF Manifest formatter to include it. Although, does the IIIF manifest have a place for descriptive metadata? 🤷‍♂️

I'm actually interested in how Mirador works with it.

**Comment by rangel35** [comment]
thanks @seth-shaw-unlv  I'll take a look at the link...the current install works great for generic books but we have legal documents that are paged and have page level metadata

@dannylamb I also noticed that if you start in page 2 it won't go to page 3 and beyond even if they do exist....this would prevent people from starting at say page 100 and continuing to finish if there is a 500 page document.

**Comment by seth-shaw-unlv** [comment]
@rangel35 I have some [basic views](https://github.com/UNLV-Libraries/islandora_unlv/blob/master/config/optional/block.block.views_block__member_of_siblings_block.yml) that help with that scenario (although they need refinement). I still need to get them to jump to a certain point in the listing... but it is better than nothing.

**Comment by rangel35** [comment]
thanks @seth-shaw-unlv  I was thinking along the lines of trying to create a block for the metadata

**Comment by dannylamb** [comment]
I've pushed up changes for autodetecting sequence mode, with collection mode overriding it if user chooses to select it.  I'm testing the build now.

**Comment by dannylamb** [comment]
This passes my smoke test and is ready to be tested by the larger group again.

**Comment by elizoller** [comment]
@seth-shaw-unlv mirador has some capabilities built in to display metadata. i'll see if i can throw together a demo of what i mean real quick.

**Comment by rangel35** [comment]
I think the main issue will be getting the page level metadata into the manifest so that mirador can access it

**Comment by elizoller** [comment]
Well instead of trying to do that in islandora real fast - https://projectmirador.org/demo/ if you click the i icon in the upper right corner you get a little metadata hover. I agree with @rangel35 it'd just be a matter of getting that into the manifest, which would probably involve some additional work in https://github.com/Islandora-CLAW/islandora/blob/8.x-1.x/modules/islandora_iiif/src/Plugin/views/style/IIIFManifest.php

**Comment by whikloj** [comment]
`vagrant up`

**Comment by elizoller** [comment]
When I run vagrant up on this I'm getting a composer error: `./composer.json has been updated`

**Comment by dannylamb** [comment]
@elizoller I was getting that earlier.  Do you have this commit? https://github.com/Islandora-Devops/claw-playbook/pull/143/commits/ff50c3a7dd473a0093ad137990138c02f190eab3

**Comment by elizoller** [comment]
No because i have claw-playbook:paged-content-config instead of dannylamb:paged-content-config :(

**Comment by whikloj** [comment]
Pro-tip: https://wiki.duraspace.org/display/FF/Guide+for+New+Developers#GuideforNewDevelopers-ConfigureforPerformingCodeReviews

Then I just do:
```
[/sw/var/www/DAM2/claw-playbook] 
> git fetch origin
remote: Enumerating objects: 18, done.
remote: Counting objects: 100% (18/18), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 30 (delta 13), reused 17 (delta 13), pack-reused 12
Unpacking objects: 100% (30/30), done.
From https://github.com/Islandora-Devops/claw-playbook
   f3be6d5..3563dca  dev                  -> origin/dev
 * [new branch]      paged-content-config -> origin/paged-content-config
   5099a15..6912b14  refs/pull/141/head   -> origin/pull/141
 + a62a8e8...4117f91 refs/pull/142/head   -> origin/pull/142  (forced update)
 * [new ref]         refs/pull/143/head   -> origin/pull/143

[/sw/var/www/DAM2/claw-playbook] 
> git checkout origin/pull/143
Note: checking out 'origin/pull/143'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at ff50c3a Missed an inventory var
```

**Comment by whikloj** [comment]
To keep this up-to-date. On the paged_content object I am seeing
```
Notice: Undefined index: #id in at_core_theme_suggestions_block_alter() (line 115 of themes/contrib/adaptivetheme/at_core/includes/suggestions.inc).

at_core_theme_suggestions_block_alter(Array, Array, 'block') (Line: 449)
Drupal\Core\Theme\ThemeManager->alterForTheme(Object, 'theme_suggestions', Array, Array, 'block') (Line: 458)
Drupal\Core\Theme\ThemeManager->alter(Array, Array, Array, 'block') (Line: 245)
Drupal\Core\Theme\ThemeManager->render('block', Array) (Line: 437)
Drupal\Core\Render\Renderer->doRender(Array) (Line: 450)
Drupal\Core\Render\Renderer->doRender(Array) (Line: 450)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 195)
Drupal\Core\Render\Renderer->render(Array) (Line: 501)
Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 72)
__TwigTemplate_62c3f4d8ab97d047fc5cc76dc106b2ac0da09586210503f6da3bfa8ed478ce17->doDisplay(Array, Array) (Line: 443)
Twig\Template->displayWithErrorHandling(Array, Array) (Line: 414)
Twig\Template->display(Array) (Line: 422)
Twig\Template->render(Array) (Line: 64)
twig_render_template('themes/contrib/adaptivetheme/at_core/templates/layout/row.html.twig', Array) (Line: 384)
Drupal\Core\Theme\ThemeManager->render('row', Array) (Line: 437)
Drupal\Core\Render\Renderer->doRender(Array) (Line: 450)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 195)
Drupal\Core\Render\Renderer->render(Array) (Line: 501)
Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 63)
__TwigTemplate_1ec3110f8b54593a7ec27ae3ad01e01d2e7188bd1a773d4909efb03da2cbc6b8->doDisplay(Array, Array) (Line: 443)
Twig\Template->displayWithErrorHandling(Array, Array) (Line: 414)
Twig\Template->display(Array) (Line: 422)
Twig\Template->render(Array) (Line: 64)
twig_render_template('themes/contrib/carapace/templates/generated/page.html.twig', Array) (Line: 384)
Drupal\Core\Theme\ThemeManager->render('page', Array) (Line: 437)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 195)
Drupal\Core\Render\Renderer->render(Array) (Line: 501)
Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 123)
__TwigTemplate_785de26570213494849bebc5870f66c8749014f7d3d42b96680dd828d65d266d->doDisplay(Array, Array) (Line: 443)
Twig\Template->displayWithErrorHandling(Array, Array) (Line: 414)
Twig\Template->display(Array) (Line: 422)
Twig\Template->render(Array) (Line: 64)
twig_render_template('themes/contrib/adaptivetheme/at_core/templates/layout/html.html.twig', Array) (Line: 384)
Drupal\Core\Theme\ThemeManager->render('html', Array) (Line: 437)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 195)
Drupal\Core\Render\Renderer->render(Array) (Line: 147)
Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() (Line: 582)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 148)
Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object, Object) (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object, 'kernel.view', Object)
call_user_func(Array, Object, 'kernel.view', Object) (Line: 111)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.view', Object) (Line: 156)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 68)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 52)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 693)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
```

@dannylamb is looking into setting the `#id` as it seems to be missing from the OSD block.

**Comment by kayakr** [comment]
I followed @whikloj's notes above but at
```
(my_env) 12:54:48 jonathan:~/Documents/CatalystIT/vagrant-claw-playbook-vm12 ((HEAD detached at origin/pull/143)) $ git branch
(HEAD detached at origin/pull/143)
```
I get 
```
TASK [Islandora-Devops.drupal-openseadragon : Install Openseadragon with
composer] *** Tuesday 01 October 2019  12:53:21 +1300 (0:00:00.120)      
0:08:26.447 ******* fatal: [default]: FAILED! => {"changed": false, "msg":
"[InvalidArgumentException] Could not find package islandora/openseadragon in
a version matching dev-paged-content-config require [--dev] [--prefer-source]
[--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts]
[--update-no-dev] [--update-with-dependencies]
[--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable]
[--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader]
[-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...",
"stdout": "\n \n  [InvalidArgumentException]                                  
                                  \n  Could not find package
islandora/openseadragon in a version matching dev-paged-content-config  \n    
                                                                              
             \n\nrequire [--dev] [--prefer-source] [--prefer-dist]
[--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev]
[--update-with-dependencies] [--update-with-all-dependencies]
[--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages]
[-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader]
[--] [<packages>]...\n\n", "stdout_lines": ["", "                             
                                                                   ", " 
[InvalidArgumentException]                                                    
                ", "  Could not find package islandora/openseadragon in a
version matching dev-paged-content-config  ", "                               
                                                                 ", "",
"require [--dev] [--prefer-source] [--prefer-dist] [--no-progress]
[--no-suggest] [--no-update] [--no-scripts] [--update-no-dev]
[--update-with-dependencies] [--update-with-all-dependencies]
[--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages]
[-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader]
[--] [<packages>]...", ""]} 
```

**Comment by kayakr** [comment]
Specifying the specific commit `openseadragon_composer_item: "islandora/openseadragon:dev-paged-content-config#fd8a775998b988d90d7e52457103c62e8e7063fc"` in `webserver/drupal.yml` allowed install to complete.

**Comment by Natkeeran** [comment]
Running into the following issue when trying to vagrant up this PR:

```
TASK [Islandora-Devops.alpaca : Add Alpaca Repos] ******************************
Tuesday 01 October 2019  12:36:42 -0400 (0:00:00.361)       0:07:02.420 ******* 
failed: [default] (item=mvn:org.apache.camel.karaf/apache-camel/2.20.4/xml/features) => {"ansible_loop_var": "item", "changed": false, "item": "mvn:org.apache.camel.karaf/apache-camel/2.20.4/xml/features", "msg": "client: Ignoring predefined value for KARAF_HOME\n"}
failed: [default] (item=mvn:org.apache.activemq/activemq-karaf/5.15.0/xml/features) => {"ansible_loop_var": "item", "changed": false, "item": "mvn:org.apache.activemq/activemq-karaf/5.15.0/xml/features", "msg": "client: Ignoring predefined value for KARAF_HOME\n"}
failed: [default] (item=mvn:ca.islandora.alpaca/islandora-karaf/1.0.1/xml/features) => {"ansible_loop_var": "item", "changed": false, "item": "mvn:ca.islandora.alpaca/islandora-karaf/1.0.1/xml/features", "msg": "client: Ignoring predefined value for KARAF_HOME\n"}

```

**Comment by dannylamb** [comment]
Just successfully spun up a box with these latest changes.  This pulls in the newest theme, which fixes an issue when placing blocks with contexts that @whikloj found.

Folks can give it a try.

**Comment by seth-shaw-unlv** [comment]
Just creating a single item in the new theme caused a bunch of log messages: 
Screen Shot 2019-10-01 at 1 07 09 PM

And it looks like we need to handle an empty IIIF manifest a bit more cleanly:
```
Warning: Invalid argument supplied for foreach() in Drupal\openseadragon\IIIFManifestParser->getTileSources() (line 96 of /var/www/html/drupal/web/modules/contrib/openseadragon/src/IIIFManifestParser.php)
#0 /var/www/html/drupal/web/core/includes/bootstrap.inc(587): _drupal_error_handler_real(2, 'Invalid argumen...', '/var/www/html/d...', 96, Array) #1 /var/www/html/drupal/web/modules/contrib/openseadragon/src/IIIFManifestParser.php(96): _drupal_error_handler(2, 'Invalid argumen...', '/var/www/html/d...', 96, Array) 
#2 /var/www/html/drupal/web/modules/contrib/openseadragon/openseadragon.module(139): Drupal\openseadragon\IIIFManifestParser->getTileSources('http://localhos...') 
#3 /var/www/html/drupal/web/core/lib/Drupal/Core/Theme/ThemeManager.php(287): template_preprocess_openseadragon_iiif_manifest_block(Array, 'openseadragon_i...', Array)
```

**Comment by elizoller** [comment]
I got similar error messages to seth but as i went further into the test i got an additional one: `EntityViewMode user.open_seadragon does not exist. View mode cannot be altered.`
although the viewer and reordering of pages did actually work

**Comment by dannylamb** [comment]
The theme update fixed a somewhat edge-y case, so we can always revert if it's problematic and leave it as a 'known issue'.  But if you're developing with caching disabled, it's fixes something pretty annoying.

@elizoller That one isn't related to the theme.  It shows up a lot anyway.  I think I just need to lower the level of that message.

@seth-shaw-unlv I think the manifest is ok and i'm not parsing it correctly.  I'll look into it.  I've made a paged content node and then been redirected to it after submitting the form so i'm surprised i haven't seen that one yet.

**Comment by dannylamb** [comment]
Oh noes... when testing the fix for @seth-shaw-unlv's empty paged content issue, I ran into a new one.  Make two books.  The block gets cached.  Visit one and then the other.  The second block is the same as for the first object.  Gotta get that caching sorted out :sob:

**Comment by dannylamb** [comment]
Alright, I pushed up some changes to openseadragon to do better caching.  Now you don't have to clear your caches all the time!

It also works if you have more than one 'paged content' object now. Good thing we caught that before the conference ^_^

I'm vagrant up'ing now to confirm.  But this should be good to test one more time.

**Comment by dannylamb** [comment]
Let me know if you want me to revert the theme changes.  Easy enough to do.

**Comment by whikloj** [comment]
Of course I started my build 20 minutes ago, or 15 minutes before the last change.

✊ LAMB!!!!

**Comment by whikloj** [comment]
Ok, I built this except for the last commit. I saw the error that you get if you have not set the IIIF Manifest. But after I set it, it does work.

The IIIF Manifest box has waaaaaay too many choices, but we can review that later.
Screen Shot 2019-10-02 at 12 26 35 PM


👍

**Comment by dannylamb** [comment]
In theory we can filter that list by views that use the iiif manifest views style plugin.  Would def cut the size of that list down.

**Comment by whikloj** [comment]
Yeah, or it would be good to more clearly define that this is a list of views and you are supposed to select one that gives the IIIF Manifest for a resource. Also that the default provided is IIIF Manifest

**Comment by dannylamb** [comment]
@whikloj Everything's been reverted to point to 8.x branches.  This is ready to go.

**Comment by whikloj** [comment]
Testing one last time.

**Comment by dannylamb** [comment]
Mine just spun up successfully :crossed_fingers:

**Pull request merged**
