### PR TITLE
bring role configs to inventory

### PR DESCRIPTION
**Pull request by Natkeeran**
!!! Please hold on testing this until the dependencies get merged. 

This PR depends on the following getting merged:
* https://github.com/Islandora-Devops/ansible-role-alpaca/pull/7
* https://github.com/Islandora-Devops/ansible-role-crayfish/pull/28

# What does this Pull Request do?
This PR make some of the variables that need to be configured for multi sever deployment explicit in the inventory.

# How should this be tested?
* After the dependent PRs are merged, get this PR
* Vagrant up
* Sanity checks

# Interested parties
 @Islandora-Devops/committers

### CODE REVIEW

**Comment by dannylamb** [comment]
FWIW i'm testing all at once by updating my `requirements.yml` file to point to your forks for the alpaca and crayfish roles, and then I pulled in this PR.  I'll let you know how it goes.

**Comment by dannylamb** [comment]
@Natkeeran Tested, works great.  I sliced `1.0.1` versions for the alpaca and crayfish roles.  Want to update `requirements.yml` to point to those and I'll merge this in?

**Comment by Natkeeran** [comment]
@dannylamb 

I am wondering if I could use {{ hostvars[groups['tomcat'][0]].ansible_ssh_host }} variables:

Example: 
https://github.com/Natkeeran/claw-playbook/commit/c747553387798c16f383debe3eaa135345db9fa4

This works.  It will put 127.0.0.1.  The only issue is that we are only using the first machine in the inventory group.  However, that is equivalent to having localhost situation right now!

**Comment by Natkeeran** [comment]
@dannylamb 

Web server port should be a variable as well!

**Comment by dannylamb** [comment]
@Natkeeran You want to toss those in now or should I just merge?

**Comment by Natkeeran** [comment]
@dannylamb 

I'll make those changes now, test it and ping you.

**Comment by Natkeeran** [comment]
@dannylamb 

If you can test/merge this https://github.com/Islandora-Devops/ansible-role-blazegraph/pull/8, I can the requirements as well.  

I am running into the following issue:
"The upload directory fedora://2019-07 for the file field field_media_image could not be created or is not accessible. A newly uploaded file could not be saved in this directory as a consequence, and the upload was canceled."

I am not sure if this related to this PR.  Going to try without these PRs.

**Comment by dannylamb** [comment]
@Natkeeran I'll give it a shot and report back.

**Comment by dannylamb** [comment]
I tested the blazegraph role along with the others and it all looks good.  I can't replicate the issue you're running into.  I uploaded an image and a video and all the viewers work, content is indexed in fedora and blazegraph.  Looks good to me.

**Comment by dannylamb** [comment]
I merged the blazegraph role.   Update `requirements.yml` and I'm happy to pull this in.

**Comment by dannylamb** [comment]
Thx @Natkeeran

**Pull request merged**
