### PR TITLE
Unpinning from 1.0.0 to dev

### PR DESCRIPTION
**Pull request by dannylamb**
# DO NOT MERGE

For https://github.com/Islandora-CLAW/CLAW/issues/1158

I've made this branch to pull all `dev` and `8.x-1.x` branches instead of using pinned versions of any Islandora 8 code. Can I get some folks to try out provisioning from the dev branch to test this?

If you can provision fine and it passes a quick smoke test, let me know and close this PR and https://github.com/Islandora-CLAW/CLAW/issues/1158

### CODE REVIEW

**Comment by whikloj** [comment]
`vagrant up`

**Comment by whikloj** [comment]
@dannylamb This worked as expected. 👍

**Comment by seth-shaw-unlv** [comment]
Also just started a `vagrant up`.

**Comment by seth-shaw-unlv** [comment]
Same here, @dannylamb, looks good.

**Pull request closed without merging**
