### PR TITLE
Updating rest config to use per method granularity

### PR DESCRIPTION
**Pull request by dannylamb**
Resolves https://github.com/Islandora-CLAW/CLAW/issues/797

Pinning down REST config for Node and Media to open up the REST api to JSON requests while only allowing the `jsonld` format for GET requests.  Allows for File deletion as well.

### CODE REVIEW

**Comment by whikloj** [comment]
The file rest config is missing because we apparently define and copy each file individually [here](https://github.com/Islandora-Devops/claw-playbook/blob/master/roles/internal/webserver-app/tasks/drupal.yml#L82-L98).

I would suggest making a variable with the names of the files to copy to the configs directory and looping through them instead of all of [this](https://github.com/Islandora-Devops/claw-playbook/blob/master/roles/internal/webserver-app/tasks/drupal.yml#L64-L98)

**Comment by whikloj** [comment]
Or actually maybe a better way is to move all the files from directly under files to a drupal subdirectory (they are all drupal files now, but if we get others we will need a separation).
```
webserver-app/files/drupal/filehash.settings.yml
```
The using the ansible [copy](http://docs.ansible.com/ansible/latest/copy_module.html) method and pointing it at the directory and making sure to end the src with a `/` it will only copy the files inside the directory to the destination directory. (Kinda like rsync).

**Comment by whikloj** [comment]
@dannylamb bump...if you have time to fix this if you don't let me know and I can do it. Just that then we need to have someone else do a merge for this. But I'd like this ready before I merge https://github.com/Islandora-CLAW/islandora/pull/76

**Comment by dannylamb** [comment]
@whikloj Hey yeah, let's move this forward.  I can take a stab at using the ansible copy method.

**Comment by dannylamb** [comment]
Ugh... getting this:

```bash
TASK [geerlingguy.drupal-console : Install Drupal Console.] ********************
Wednesday 07 March 2018  11:06:13 -0400 (0:00:00.037)       0:17:41.111 ******* 
fatal: [default]: FAILED! => {"changed": false, "dest": "/usr/local/bin/drupal", "msg": "Request failed", "response": "HTTP Error 500: Internal Server Error", "state": "absent", "status_code": 500, "url": "https://drupalconsole.com/installer"}
```

Looks like the https://drupalconsole.com/installer is redirecting to a nonexistant download link on Github.

**Comment by dannylamb** [comment]
FYI https://gitter.im/hechoendrupal/DrupalConsole?at=5aa01478e4ff28713a0575ea

**Comment by dannylamb** [comment]
@whikloj And https://gitter.im/hechoendrupal/DrupalConsole?at=5aa0179de4d1c63604d27192

Looks like this'll work now.  I'm spinning it up again now

**Comment by dannylamb** [comment]
@whikloj So my install is still churning but at least I've made it past what I changed and I can verify the copy command works fine.  

```bash
ubuntu@claw:/var/www/html/drupal$ cd /opt/islandora/configs/drupal
ubuntu@claw:/opt/islandora/configs/drupal$ ls
block.block.views_block__membership_view_block_1.yml  rest.resource.entity.file.yml   rest.resource.entity.node.yml
filehash.settings.yml                                 rest.resource.entity.media.yml  ubuntu-xenial-16.04-cloudimg-console.log
```
And it does get imported:
```bash
ubuntu@claw:/var/www/html/drupal/web/modules/contrib/islandora$ drush cget rest.resource.entity.node
uuid: a2600075-16ed-47ee-bdae-b7c8ec049ff5
langcode: en
status: true
dependencies:
  module:
    - basic_auth
    - jsonld
    - jwt
    - node
    - serialization
    - user
_core:
  default_config_hash: t_jfECmZhJqBOJuSOFn87EOi_TWi-_fRYTuJgd19vgg
id: entity.node
plugin_id: 'entity:node'
granularity: method
configuration:
  GET:
    supported_formats:
      - jsonld
      - json
    supported_auth:
      - basic_auth
      - jwt_auth
      - cookie
  POST:
    supported_formats:
      - json
    supported_auth:
      - basic_auth
      - jwt_auth
  DELETE:
    supported_formats:
      - json
    supported_auth:
      - basic_auth
      - jwt_auth
  PATCH:
    supported_formats:
      - json
    supported_auth:
      - basic_auth
      - jwt_auth

```

The full install hasn't played out, but we're probably gtg on this one.

**Pull request merged**
