### PR TITLE
Don't separately install drush

### PR DESCRIPTION
**Pull request by rosiel**
**GitHub Issue**: https://github.com/Islandora-Devops/islandora-playbook/issues/269

# What does this Pull Request do?

There are two things in this PR:
- add `vagrant_user` in the Vagrant file. Without this, the Vagrant installation doesn't work. I'm not sure how it worked before.
- fixes proposed by @RodBruce (many thanks!) for installing Drupal 10 (namely, _not_ installing the Drush Installer.)

Drush is still installed, but because it's required by the Starter Site or (hopefully) whatever you're using in place of the starter site. This is how it's supposed to be installed.

# What's new?

* Adds a value to `ansible_user` in the Vagrantfile
* Removes the `geerlingguy.drush` playbook role from `requirements.yml`
* Removes the call to that role in `webserver.yml`.

In regard to change number 3 in the linked issue, I found that i did not have to change anything in the drupal playbook for it to work. When Composer deployed the drupal project from the starter site, drush 12 was installed into the /vendor/bin folder. The [Drupal ansible role looks in this folder for Drush](https://github.com/geerlingguy/ansible-role-drupal/blob/master/tasks/main.yml#L43-L52). I ran the playbook using Vagrant with no other alterations (your change no.1 to the playbook version string has already been merged) and I got a Drupal 10.1.5 site with no Playbook errors. 

* Does this change require documentation to be updated?  No
* Does this change add any new dependencies? No
* Does this change require any other modifications to be made to the repository
 (i.e. Regeneration activity, etc.)? No
* Could this change impact execution of existing code? No

# How should this be tested?

* clone this repo
* type `vagrant up` or use the [deploy instructions](https://islandora.github.io/documentation/installation/playbook/#deploying-to-a-remote-environment) to deploy it to another server.

# Additional Notes:
Any additional information that you think would be helpful when reviewing this
 PR.

# Interested parties
Tag (@ mention) interested parties or, if unsure, @Islandora-Devops/committers

### CODE REVIEW

**Comment by noahwsmith** [comment]
Maybe @whikloj should review this - looking at commit history he may be the only active committer that uses the Playbook?

**Comment by seth-shaw-asu** [comment]
@whikloj has a new Mac and can't run the playbook anymore. I'll review it.

**Comment by whikloj** [comment]
Thank you @seth-shaw-asu , I did try to switch to using Packer but haven't been successful yet

**Comment by BrzIGH** [comment]
Sorry to report that this does not currently work...keeps failing at the ansible "false" command.

**Comment by seth-shaw-asu** [comment]
Sorry for the delay. I've been struck down by illness and not getting better as quickly as anticipated. I'll test after I get better.

**Comment by BrzIGH** [comment]
No problem. Get better first. Business can come second :-)

**Review by seth-shaw-asu — APPROVED** [review]
Ran without error and Drush is accessible after launch.

**Comment by BrzIGH** [comment]
Thank you. Will try again once I am back in the office...

**Comment by BrzIGH** [comment]
I am at a loss...still ran into the same problem even after reverting to a base Ubuntu server snapshot and redoing the same steps that I did before Christmas.... (download playbook and edit files as per "Deplying to a remote environment" web document.... :-(

TASK [geerlingguy.drupal : Move Drupal project files to drupal_composer_install_dir (this may take a while).] ***************************************************************************
Friday 19 January 2024  10:30:49 -0800 (0:00:00.273)       0:00:28.835 ******** 
changed: [default]

TASK [geerlingguy.drupal : Install dependencies with composer require (this may take a while).] *****************************************************************************************
Friday 19 January 2024  10:30:54 -0800 (0:00:04.593)       0:00:33.429 ******** 
failed: [default] (item=drush/drush:^10.1) => {"ansible_loop_var": "item", "changed": false, "item": "drush/drush:^10.1", "msg": "./composer.json has been updated Running composer update drush/drush Loading composer repositories with package information Updating dependencies Your requirements could not be resolved to an installable set of packages. Problem 1 - drush/drush[10.1.0, ..., 10.3.1] require chi-teck/drupal-code-generator ^1.30.5 -> found chi-teck/drupal-code-generator[1.30.5, ..., 1.x-dev] but the package is fixed to 3.3.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command. - drush/drush[10.3.2, ..., 10.x-dev] require chi-teck/drupal-code-generator ^1.32.1 -> found chi-teck/drupal-code-generator[1.32.1, 1.33.0, 1.33.1, 1.x-dev] but the package is fixed to 3.3.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command. - Root composer.json requires drush/drush ^10.1 -> satisfiable by drush/drush[10.1.0, ..., 10.x-dev]. Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions. Installation failed, reverting ./composer.json and ./composer.lock to their original content.", "stdout": "./composer.json has been updated\nRunning composer update drush/drush\nLoading composer repositories with package information\nUpdating dependencies\nYour requirements could not be resolved to an installable set of packages.\n\n  Problem 1\n    - drush/drush[10.1.0, ..., 10.3.1] require chi-teck/drupal-code-generator ^1.30.5 -> found chi-teck/drupal-code-generator[1.30.5, ..., 1.x-dev] but the package is fixed to 3.3.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.\n    - drush/drush[10.3.2, ..., 10.x-dev] require chi-teck/drupal-code-generator ^1.32.1 -> found chi-teck/drupal-code-generator[1.32.1, 1.33.0, 1.33.1, 1.x-dev] but the package is fixed to 3.3.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.\n    - Root composer.json requires drush/drush ^10.1 -> satisfiable by drush/drush[10.1.0, ..., 10.x-dev].\n\nUse the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.\n\nInstallation failed, reverting ./composer.json and ./composer.lock to their original content.\n", "stdout_lines": ["./composer.json has been updated", "Running composer update drush/drush", "Loading composer repositories with package information", "Updating dependencies", "Your requirements could not be resolved to an installable set of packages.", "", "  Problem 1", "    - drush/drush[10.1.0, ..., 10.3.1] require chi-teck/drupal-code-generator ^1.30.5 -> found chi-teck/drupal-code-generator[1.30.5, ..., 1.x-dev] but the package is fixed to 3.3.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.", "    - drush/drush[10.3.2, ..., 10.x-dev] require chi-teck/drupal-code-generator ^1.32.1 -> found chi-teck/drupal-code-generator[1.32.1, 1.33.0, 1.33.1, 1.x-dev] but the package is fixed to 3.3.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.", "    - Root composer.json requires drush/drush ^10.1 -> satisfiable by drush/drush[10.1.0, ..., 10.x-dev].", "", "Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.", "", "Installation failed, reverting ./composer.json and ./composer.lock to their original content."]}

**Comment by rosiel** [comment]
You don't need to post this twice.

**Comment by BrzIGH** [comment]
Yes, I am sorry...I do not hang out on github too much...I still find it confusing to navigate...

**Comment by BrzIGH** [comment]
Yes, I am sorry. I do not hang out on github too often. I find it a tad confusing to navigate.

**Pull request merged**
