### PR TITLE
no gemini

### PR DESCRIPTION
**Pull request by dannylamb**
**GitHub Issue**: playbook analog of https://github.com/Islandora-Devops/isle-dc/pull/132

# What does this Pull Request do?
Deploys islandora sans gemini

# How should this be tested?

* Pull in this PR
* `rm -rf roles/external`
* Assuming you're testing locally, youll want to set these configs in `inventory/vagrant/group_vars/crayfish.yml` to localhost.  If you're testing remotely keeping it is fine, the IP will work. But if you're local,  you get 127.0.0.1 which doesn't quite work.  Drupal thinks its localhost and the string matching in recast will fail. So TL;DR do this:
```
crayfish_fedora_base_url: "localhost:8080/fcrepo/rest"
crayfish_drupal_base_url: "localhost:{{ apache_listen_port }}"
```
* `vagrant up`
* Go make content and follow its "Fedora URI" link to Fedora, confirm the 
* Use Recast on some of your content and confirm it turns drupal urls into fedora urls:
```
vagrant@islandora8:~$ curl -H "Authorization: Bearer islandora" -H "Apix-Ldp-Resource: http://localhost:8080/fcrepo/rest/73/63/a8/93/7363a893-67ce-41aa-8d18-a4b8323d4171" localhost:8000/recast/replace
@prefix fedora: <http://fedora.info/definitions/v4/repository#> .
@prefix ldp: <http://www.w3.org/ns/ldp#> .
@prefix pcdm: <http://pcdm.org/models#> .
@prefix schema: <http://schema.org/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix dc: <http://purl.org/dc/terms/> .

<http://localhost:8080/fcrepo/rest/73/63/a8/93/7363a893-67ce-41aa-8d18-a4b8323d4171>
  a fedora:Container, <http://purl.org/coar/resource_type/c_c513>, fedora:Resource, ldp:BasicContainer, pcdm:Object, ldp:RDFSource, ldp:Container ;
  fedora:lastModifiedBy "bypassAdmin" ;
  schema:dateModified "2021-03-11T15:34:37+00:00"^^xsd:dateTime ;
  schema:author <http://localhost:8000/user/1> ;
  schema:sameAs <http://localhost:8000/node/2> ;
  schema:dateCreated "2021-03-11T15:33:55+00:00"^^xsd:dateTime ;
  dc:extent "1 item" ;
  fedora:createdBy "bypassAdmin" ;
  fedora:lastModified "2021-03-11T15:34:38.683Z"^^xsd:dateTime ;
  fedora:created "2021-03-11T15:34:38.683Z"^^xsd:dateTime ;
  pcdm:memberOf <http://localhost:8080/fcrepo/rest/36/8a/e0/e2/368ae0e2-649f-48c6-b7c3-537fc4d00565> ;
  dc:title "An Item"@en .

```

# Interested parties
@Islandora-Devops/committers

### CODE REVIEW

**Comment by elizoller** [comment]
i'll give this a whirl since i can't get recast to work when i manually updated the components in vagrant

**Comment by elizoller** [comment]
Thats not working for me either.
I spun this up. Made items. 
`curl -H "Authorization: Bearer islandora" -H "Apix-Ldp-Resource: http://localhost:8080/fcrepo/rest/5c/2d/1b/67/5c2d1b67-fb46-4584-9737-990130614edd" localhost:8000/recast/replace`
where i grabbed the fedora URI from the browser
I got this
```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="robots" content="noindex,nofollow" />
        <style>                body { background-color: #fff; color: #222; font: 16px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; margin: 0; }
                .container { margin: 30px; max-width: 600px; }
                h1 { color: #dc3545; font-size: 24px; }</style>
    </head>
    <body>
                        <div class="container">
                    <h1>Whoops, looks like something went wrong.</h1>
                </div>
    </body>
    ```

and in the recast log:
```
[2021-03-11 15:51:49] app.CRITICAL: GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: lohttp (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) (uncaught exception) at /var/www/html/Crayfish/Recast/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php line 200 {"exception":"[object] (GuzzleHttp\\Exception\\ConnectException(code: 0): cURL error 6: Could not resolve host: lohttp (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) at /var/www/html/Crayfish/Recast/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:200)"} []
[2021-03-11 15:51:49] app.DEBUG: < 500 [] []
```

**Comment by elizoller** [comment]
I'm in business!!!!!

**Comment by elizoller** [comment]
`curl -H "Authorization: Bearer islandora" -H "Apix-Ldp-Resource: http://localhost:8080/fcrepo/rest/5c/2d/1b/67/5c2d1b67-fb46-4584-9737-990130614edd" localhost:8000/recast/replace`
returned
```
@prefix fedora: <http://fedora.info/definitions/v4/repository#> .
@prefix ldp: <http://www.w3.org/ns/ldp#> .
@prefix pcdm: <http://pcdm.org/models#> .
@prefix schema: <http://schema.org/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix ns0: <http://id.loc.gov/vocabulary/relators/> .
@prefix dc: <http://purl.org/dc/terms/> .

<http://localhost:8080/fcrepo/rest/5c/2d/1b/67/5c2d1b67-fb46-4584-9737-990130614edd>
  a fedora:Container, <http://purl.org/coar/resource_type/c_c513>, fedora:Resource, ldp:BasicContainer, pcdm:Object, ldp:RDFSource, ldp:Container ;
  fedora:lastModifiedBy "bypassAdmin" ;
  schema:dateModified "2021-03-11T20:16:41+00:00"^^xsd:dateTime ;
  schema:author <http://localhost:8000/user/1> ;
  ns0:prv <http://localhost:8080/fcrepo/rest/71/0e/26/0a/710e260a-f0bc-4d39-ae6a-d1f5b9d20031>, <http://localhost:8080/fcrepo/rest/6e/25/24/2c/6e25242c-cbe6-43aa-9b6b-ece655c1db14> ;
  schema:sameAs <http://localhost:8000/node/5> ;
  schema:dateCreated "2021-03-11T20:16:41+00:00"^^xsd:dateTime ;
  ns0:pht <http://localhost:8080/fcrepo/rest/e2/67/5e/50/e2675e50-1a57-4eed-9462-265cdb595984> ;
  dc:date "2018-05-01", "2018-05-01"^^xsd:date ;
  dc:extent "1 item" ;
  fedora:createdBy "bypassAdmin" ;
  fedora:lastModified "2021-03-11T20:16:47.904Z"^^xsd:dateTime ;
  fedora:created "2021-03-11T20:16:47.904Z"^^xsd:dateTime ;
  dc:subject <http://localhost:8080/fcrepo/rest/bb/5d/7e/18/bb5d7e18-022a-42cc-8b1b-2142e4ec4021> ;
  dc:description "A neon sign on a multi-colored wall that reads \"This Must Be The Place\""@en ;
  dc:title "This Must Be The Place"@en .
```

**Comment by dannylamb** [comment]
This is good to go once https://github.com/Islandora-Devops/ansible-role-crayfish/pull/37 is merged

**Review by elizoller — APPROVED** [review]
Confirmed working playbook previously with all the no-gemini branches attached

**Pull request merged**
