### PR TITLE
retries and checks

### PR DESCRIPTION
**Pull request by DonRichards**
**GitHub Issue**: Not sure

# What does this Pull Request do?
Adds tags, checks and retries

# What's new?
tags, checks and retries

# How should this be tested?
change the URL of the solr zip to something that will fail to see if it actually fails.

# Additional Notes:
N/A

# Interested parties
@Islandora-Devops/committers

### CODE REVIEW

**Comment by dannylamb** [comment]
Hey nice @DonRichards ! I take it this is a pattern we can use all over the place?

**Comment by DonRichards** [comment]
@dannylamb Mostly, I'm trying to see what can be done with "unarchive". It looks highly limited but switching it to 2 functions (1 to download and the other to unarchive) seems to be the only solution I'm finding to make sure a file downloaded before moving on.

**Comment by DonRichards** [comment]
```yaml
register: solr_config_download_and_extract
until: solr_config_download_and_extract is not failed
retries: 5
tags: solr
```

But the format should work. It requires a unique `registered` label
Everything has a '**failed**' (either true or false) status so `Until` requires the register label followed by `is not failed` 
retries default to 3 (although in the PR is 5, I'm toying with 15 with success almost 100% of the time). 
Tags should stay consistent to help with debugging

**Comment by DonRichards** [comment]
Argggg..... Pushed to the wrong branch.

**Comment by seth-shaw-unlv** [comment]
@DonRichards, rather than squashing the warning, would it make sense to use the [uri module](https://docs.ansible.com/ansible/latest/modules/uri_module.html) like it recommends?

**Comment by DonRichards** [comment]
Sounds good, I'll make the change.

**Comment by seth-shaw-unlv** [comment]
Sweet. I'm building a box right now but I'll give this a spin after that one completes.

**Comment by DonRichards** [comment]
The delay looks long. I'm gonna fix that.

**Comment by DonRichards** [comment]
Sorry about that. 30 seconds seemed too long between retries. I think 20 retries of a 60 second period should work.

**Comment by DonRichards** [comment]
Ready to test.

**Comment by seth-shaw-unlv** [comment]
vagrant 🚀

**Comment by seth-shaw-unlv** [comment]
Looks good to me. :shipit:

**Pull request merged**
