### PR TITLE
Changes for Fedora 5.0.0

### PR DESCRIPTION
**Pull request by whikloj**
Related to https://github.com/Islandora-CLAW/CLAW/issues/966

Associated PRs:
* https://github.com/Islandora-CLAW/Syn/pull/14
* https://github.com/Islandora-Devops/ansible-role-fcrepo/pull/3
* https://github.com/Islandora-Devops/ansible-role-fcrepo-syn/pull/6

This PR adds the configuration parameters to use Fedora 5 and along with https://github.com/Islandora-CLAW/islandora_demo/pull/10 allows the `admin` user to push objects to Fedora by default.

There is an outstanding issue where Taxonomy terms don't get synced to Fedora, it is being tracked at https://github.com/Islandora-CLAW/CLAW/issues/988

## How to test

1. Pull down this PR.
1. Delete the below role directories
    * `./roles/external/Islandora-Devops.fcrepo`
    * `./roles/external/Islandora-Devops.fcrepo-syn`
1. Apply [this patch](https://gist.github.com/whikloj/17307967d8832c9f2e3a896284b978e8) to your claw-playbook.
1. Run `vagrant up --no-provision`
1. Run `ansible-galaxy install --roles-path=roles/external --role-file=requirements.yml`
1. Edit the file `./roles/external/Islandora-Devops.fcrepo-syn/tasks/install.yml`
      1. Edit line 12 to be 
         ```
          url: https://github.com/whikloj/Syn/releases/download/v{{ fcrepo_syn_version }}/islandora-syn-{{ fcrepo_syn_version }}-all.jar
          ```
1. Run `ansible-playbook -i inventory/vagrant -u vagrant -e 'islandora_distro=ubuntu/xenial64' playbook.yml`

Once it comes up your should have a fully functional Islandora.

But if you try to PUT directly to Fedora without a valid JWT or static token you will be denied.
```
> curl -i -XPUT http://localhost:8080/fcrepo/rest/forbid
HTTP/1.1 401 Unauthorized
Server: Apache-Coyote/1.1
Content-Type: text/html;charset=utf-8
Content-Language: en
Content-Length: 1068
Date: Fri, 14 Dec 2018 21:06:35 GMT

<!DOCTYPE html><html><head><title>Apache Tomcat/8.0.32 (Ubuntu) - Error report</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}.line {height: 1px; background-color: #525D76; border: none;}</style> </head><body><h1>HTTP Status 401 - Token authentication failed.</h1><div class="line"></div><p><b>type</b> Status report</p><p><b>message</b> <u>Token authentication failed.</u></p><p><b>description</b> <u>This request requires HTTP authentication.</u></p><hr class="line"><h3>Apache Tomcat/8.0.32 (Ubuntu)</h3></body></html>%

> curl -i -XPUT http://localhost:8080/fcrepo/rest/forbid -H"Authorization: Bearer bob"
HTTP/1.1 401 Unauthorized
Server: Apache-Coyote/1.1
Content-Type: text/html;charset=utf-8
Content-Language: en
Content-Length: 1068
Date: Fri, 14 Dec 2018 21:06:46 GMT

<!DOCTYPE html><html><head><title>Apache Tomcat/8.0.32 (Ubuntu) - Error report</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}.line {height: 1px; background-color: #525D76; border: none;}</style> </head><body><h1>HTTP Status 401 - Token authentication failed.</h1><div class="line"></div><p><b>type</b> Status report</p><p><b>message</b> <u>Token authentication failed.</u></p><p><b>description</b> <u>This request requires HTTP authentication.</u></p><hr class="line"><h3>Apache Tomcat/8.0.32 (Ubuntu)</h3></body></html>%

> curl -i -XPUT http://localhost:8080/fcrepo/rest/forbid -H"Authorization: Bearer islandora"
HTTP/1.1 201 Created
Server: Apache-Coyote/1.1
Cache-Control: private
Expires: Thu, 01 Jan 1970 00:00:00 UTC
Set-Cookie: JSESSIONID=5E033FE18EFCEE1B60FC6AB3F7308A92; Path=/fcrepo/; HttpOnly
Set-Cookie: rememberMe=deleteMe; Path=/fcrepo; Max-Age=0; Expires=Thu, 13-Dec-2018 21:06:51 GMT
ETag: W/"eb893e43e9a05ccdde02b141dd50d0382452010e"
Last-Modified: Fri, 14 Dec 2018 21:06:51 GMT
Link: <http://localhost:8080/fcrepo/rest/forbid>; rel="timegate"
Link: <http://localhost:8080/fcrepo/rest/forbid>; rel="original"
Link: <http://localhost:8080/fcrepo/rest/forbid/fcr:versions>; rel="timemap"
Link: <http://mementoweb.org/ns#OriginalResource>; rel="type"
Link: <http://mementoweb.org/ns#TimeGate>; rel="type"
Link: <http://localhost:8080/fcrepo/rest/forbid/fcr:acl>; rel="acl"
Location: http://localhost:8080/fcrepo/rest/forbid
Content-Type: text/plain
Content-Length: 40
Date: Fri, 14 Dec 2018 21:06:51 GMT

http://localhost:8080/fcrepo/rest/forbid
```

@Islandora-Devops/committers @dannylamb

### CODE REVIEW

**Comment by mjordan** [comment]
@whikloj will test over the weekend.

**Comment by mjordan** [comment]
All went well up to setp 7, where the Drupal installation failed, from what I can tell at `You are about to DROP all tables in your 'drupal8' database.`:

```
TASK [geerlingguy.drupal : Install Drupal with drush.] **********************************************************************
Sunday 16 December 2018  09:25:21 -0800 (0:00:00.040)       0:07:05.081 ******* 
fatal: [default]: FAILED! => {"changed": true, "cmd": ["/var/www/html/drupal/vendor/drush/drush/drush", "site-install", "standard", "-y", "--root=/var/www/html/drupal/web", "--site-name=Islandora-CLAW", "--account-name=admin", "--account-pass=islandora", "--db-url=mysql://drupal8:islandora@127.0.0.1/drupal8"], "delta": "0:00:01.374657", "end": "2018-12-16 17:25:21.455944", "msg": "non-zero return code", "rc": 1, "start": "2018-12-16 17:25:20.081287", "stderr": " [notice] Starting Drupal installation. This takes a while. Consider using the --notify global option.\n\nIn install.core.inc line 2280:\n                                                           \n  File system: Writable (<em>public</em> download method)  \n                                                           \n  Array                                                    \n                                                           \n\nsite:install [--db-url DB-URL] [--db-prefix DB-PREFIX] [--db-su DB-SU] [--db-su-pw DB-SU-PW] [--account-name [ACCOUNT-NAME]] [--account-mail [ACCOUNT-MAIL]] [--site-mail [SITE-MAIL]] [--account-pass ACCOUNT-PASS] [--locale [LOCALE]] [--site-name [SITE-NAME]] [--site-pass SITE-PASS] [--sites-subdir SITES-SUBDIR] [--config-dir CONFIG-DIR] [--existing-config] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--notify [NOTIFY]] [--druplicon] [--xh-link XH-LINK] [--] <command> [<profile>]...", "stderr_lines": [" [notice] Starting Drupal installation. This takes a while. Consider using the --notify global option.", "", "In install.core.inc line 2280:", "                                                           ", "  File system: Writable (<em>public</em> download method)  ", "                                                           ", "  Array                                                    ", "                                                           ", "", "site:install [--db-url DB-URL] [--db-prefix DB-PREFIX] [--db-su DB-SU] [--db-su-pw DB-SU-PW] [--account-name [ACCOUNT-NAME]] [--account-mail [ACCOUNT-MAIL]] [--site-mail [SITE-MAIL]] [--account-pass ACCOUNT-PASS] [--locale [LOCALE]] [--site-name [SITE-NAME]] [--site-pass SITE-PASS] [--sites-subdir SITES-SUBDIR] [--config-dir CONFIG-DIR] [--existing-config] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--notify [NOTIFY]] [--druplicon] [--xh-link XH-LINK] [--] <command> [<profile>]..."], "stdout": "\n // You are about to DROP all tables in your 'drupal8' database. Do you want to \n // continue?: yes.                                                             ", "stdout_lines": ["", " // You are about to DROP all tables in your 'drupal8' database. Do you want to ", " // continue?: yes.                                                             "]}
	to retry, use: --limit @/home/mark/Documents/hacking/vagrants/claw-playbook/playbook.retry
```
I reran ansible as recommended:
```
ansible-playbook --limit @/home/mark/Documents/hacking/vagrants/claw-playbook/playbook.retry -i inventory/vagrant -u vagrant -e 'islandora_distro=ubuntu/xenial64' playbook.yml
```

but got the same result. My Drupal now shows the default installation page. Here's the recap:

```
Sunday 16 December 2018  09:33:32 -0800 (0:00:01.047)       0:06:32.896 ******* 
=============================================================================== 
geerlingguy.drupal : Install dependencies with composer require (this may take a while). --------------------------- 322.30s
install extra packages ubuntu ---------------------------------------------------------------------------------------- 6.63s
geerlingguy.php : Ensure configuration directories exist. ------------------------------------------------------------ 2.65s
geerlingguy.solr : Ensure dependencies are installed. ---------------------------------------------------------------- 2.17s
geerlingguy.php : Ensure APCu config file is present. ---------------------------------------------------------------- 2.16s
geerlingguy.php : Ensure OpCache config file is present. ------------------------------------------------------------- 2.15s
geerlingguy.php : Place PHP configuration file in place. ------------------------------------------------------------- 2.13s
install aptitude ----------------------------------------------------------------------------------------------------- 1.80s
geerlingguy.php : Check for existing APCu config files. -------------------------------------------------------------- 1.46s
geerlingguy.php : Check for existing OpCache config files. ----------------------------------------------------------- 1.43s
geerlingguy.solr : Apply Solr configuration changes. ----------------------------------------------------------------- 1.35s
gather facts --------------------------------------------------------------------------------------------------------- 1.13s
geerlingguy.drupal : Install Drupal with drush. ---------------------------------------------------------------------- 1.05s
geerlingguy.solr : Remove the downloaded Solr archive. --------------------------------------------------------------- 0.98s
Gathering Facts ------------------------------------------------------------------------------------------------------ 0.96s
geerlingguy.apache : Enable Apache mods. ----------------------------------------------------------------------------- 0.94s
geerlingguy.mysql : Copy my.cnf global MySQL configuration. ---------------------------------------------------------- 0.91s
Gathering Facts ------------------------------------------------------------------------------------------------------ 0.82s
Gathering Facts ------------------------------------------------------------------------------------------------------ 0.82s
geerlingguy.java : Ensure Java is installed. ------------------------------------------------------------------------- 0.79s
```

Did I miss a step somewhere?

**Comment by mjordan** [comment]
FYI I stashed the changes to claw-playbook, checked out the master branch, and reran `ansible-playbook -i inventory/vagrant -u vagrant -e 'islandora_distro=ubuntu/xenial64' playbook.yml` with the same result.

**Comment by dannylamb** [comment]
@mjordan @whikloj Spinning one up now to see if I can reproduce.

**Comment by dannylamb** [comment]
@mjordan Mine's not done yet, but it has successfully made it past installing drupal with drush.  Not sure which step you could've missed that would affect that particular command, though.  If all else fails, maybe re-clone it down from github so you know your claw-playbook directory is fresh.  I had to do that a couple of weeks ago.

**Comment by mjordan** [comment]
@dannylamb OK, will try, thanks.

**Comment by dannylamb** [comment]
@whikloj :champagne: Works.  I don't have the taxonomy terms in Fedora because of https://github.com/Islandora-CLAW/CLAW/issues/988, but I just made an image and it got sent to Fedora and derivatives were made.  I also tested it through the command line like you suggested and things worked as expected.

How should we proceed here?  Merge and slice versions for the roles, then the same for Syn.  Then this?

**Comment by whikloj** [comment]
I think this definitely goes last, because I could add a final commit updating the `requirements.yml` to the correct versions. Other than that, the order is not as important. 

One thing I did notice is that I didn't update the `syn-settings.xml` with the **ansible-role-crayfish** to include the `header` attribute. It is not needed in Crayfish, but does make that syn-settings appear different from the one in Syn. 

Should I add a PR to it to add a value (maybe a default "no-used") for the `header` attribute on that role?

**Comment by mjordan** [comment]
Ninja'd by @dannylamb, but I did get it to install after recloning claw-playbook into a clean directory. Passes all smoke tests outlined above.

**Comment by dannylamb** [comment]
@whikloj For uniformity and clarity, sure, but that can be done after we pull in the working code :+1:

**Comment by dannylamb** [comment]
@whikloj I'll merge as soon as you update `requirements.yml` to point to all the new versions I just sliced for Syn, ansible-role-fcrepo, and ansible-role-fcrepo-syn.

**Comment by whikloj** [comment]
Bumped the versions and added the `--userid` option for the migration. My test worked, but you all give it a run too.

**Comment by dannylamb** [comment]
@whikloj Will do.  Thx for adding the `--userid` param :heart:

**Comment by dannylamb** [comment]
Renamed from `0.3.0` to `v0.3.0` and am reprovisioning now

**Comment by dannylamb** [comment]
...and we should take note of that naming conventions so I don't derp this up again.

**Comment by dannylamb** [comment]
Looks good.  Tags were in Fedora from the migration that ansible ran.  Could make objects and got derivatives. :+1:

**Pull request merged**
