### PR TITLE
ufw install and apply rules

### PR DESCRIPTION
**Pull request by Natkeeran**
## What does this Pull Request do?
* This PR installs ufw firewall and adds basic rules.  

## How should this be tested?
* Get PR
* SSH into vagrant, check ufw status: `sudo ufw status`.  Should say it is active and list the allowed ports.
* CRUD tests
* This need to be tested in all supported environments 

## Interested parties
@dannylamb @whikloj @jonathangreen

### CODE REVIEW

**Comment by jonathangreen** [comment]
I can totally see how this would be handy on a real server, but I can also see it being a bit of a pain in the butt when doing development on a throwaway vagrant box. Maybe we could wrap the role install in a `when:` statement, so it can be disabled?

**Comment by Natkeeran** [comment]
@jonathangreen Yes, agree with that approach.  Should I check for a specific variable in the when statement such as install_ufw?

**Comment by jonathangreen** [comment]
Yes I like that. Maybe something like: 
```yaml
  roles:
      - role: ufw-rules
        when: install_ufw
```

**Comment by Natkeeran** [comment]
I separated the role: https://github.com/Natkeeran/ansible-role-ufw

It has ` franklinkim.ufw` as a dependency.

@dannylamb  @jonathangreen @whikloj 

Should we make this an optional role?

**Comment by whikloj** [comment]
@Natkeeran as this is now an external role, do you want to add some information to the docs on how you could add and use it to secure your and close this?

**Comment by Natkeeran** [comment]
This is an external optional role.  Closing this PR.

**Pull request closed without merging**
