### PR TITLE
Pinning islandora_fits

### PR DESCRIPTION
**Pull request by dannylamb**
**GitHub Issue**: https://github.com/Islandora/documentation/issues/1405

# What does this Pull Request do?

Pins `islandora_fits` to the last known working version.

# How should this be tested?

#### Original Behaviour
Create a resource node and give it an original file.  You'll whitescreen with this in `/var/log/apache2/error.log`
```
[Tue Jan 21 14:27:43.053575 2020] [php7:notice] [pid 814] [client 10.0.2.2:48366] Uncaught PHP Exception Drupal\\Core\\Entity\\EntityStorageException: "Field field_fits_file is unknown." at /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php line 847, referer: http://localhost:8000/media/add/image?edit%5Bfield_media_of%5D%5Bwidget%5D%5B0%5D%5Btarget_id%5D=2
```

#### Behaviour with this PR
Save an Original File to a resource node and you'll have no whitescreen and nothing but your derivatives and happy times :rainbow: 

# Interested parties
@Islandora-Devops/committers

### CODE REVIEW

**Comment by mjordan** [comment]
It would be great if we can avoid specifics like "rdm" in module names and code. I understand the amount of work involved in changing module names, but for modules and other code that have applicability outside the original context the code was developed for, more generic names will lead to a cleaner, more understandable codebase in the future.

**Comment by dannylamb** [comment]
Ideally this would reside in the islandora org and under the islandora namespace in packagist.

**Comment by Natkeeran** [comment]
Running into the following issue with this PR:

```
TASK [Islandora-Devops.fits : Download Islandora FITS] *************************
Tuesday 28 January 2020  12:29:07 -0500 (0:00:16.639)       0:21:55.431 ******* 
fatal: [default]: FAILED! => {"changed": false, "msg": "Do not run Composer as root/super user! See https://getcomposer.org/root for details Using version dev-master for islandora-rdm/islandora_fits ./composer.json has been updated > DrupalProject\\composer\\ScriptHandler::checkComposerVersion Loading composer repositories with package information Updating dependencies (including require-dev) Package operations: 0 installs, 1 update, 0 removals - Updating islandora-rdm/islandora_fits dev-master (b8a126e => 106ed01): Installation failed, reverting ./composer.json to its original content. [RuntimeException] Source directory web/modules/contrib/islandora_fits has unpushed changes on the current branch: M config/install/field.storage.media.fits_ois_file_information_md5che.yml A islandora_fits.links.menu.yml M islandora_fits.module A islandora_fits.routing.yml A src/Controller/IslandoraFitsDerivativeController.php A src/Form/AdminForm.php M src/Plugin/Action/GenerateFitsDerivative.php A src/Plugin/Action/GenerateFitsDerivativeFile.php M src/Services/XMLTransform.php M templates/fits.html.twig require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...", "stdout": "Do not run Composer as root/super user! See https://getcomposer.org/root for details\nUsing version dev-master for islandora-rdm/islandora_fits\n./composer.json has been updated\n> DrupalProject\\composer\\ScriptHandler::checkComposerVersion\nLoading composer repositories with package information\nUpdating dependencies (including require-dev)\nPackage operations: 0 installs, 1 update, 0 removals\n  - Updating islandora-rdm/islandora_fits dev-master (b8a126e => 106ed01): \nInstallation failed, reverting ./composer.json to its original content.\n\n                                                                                                    \n  [RuntimeException]                                                                                \n  Source directory web/modules/contrib/islandora_fits has unpushed changes on the current branch:   \n  M\tconfig/install/field.storage.media.fits_ois_file_information_md5che.yml                         \n  A\tislandora_fits.links.menu.yml                                                                   \n  M\tislandora_fits.module                                                                           \n  A\tislandora_fits.routing.yml                                                                      \n  A\tsrc/Controller/IslandoraFitsDerivativeController.php                                            \n  A\tsrc/Form/AdminForm.php                                                                          \n  M\tsrc/Plugin/Action/GenerateFitsDerivative.php                                                    \n  A\tsrc/Plugin/Action/GenerateFitsDerivativeFile.php                                                \n  M\tsrc/Services/XMLTransform.php                                                                   \n  M\ttemplates/fits.html.twig                                                                        \n                                                                                                    \n\nrequire [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...\n\n", "stdout_lines": ["Do not run Composer as root/super user! See https://getcomposer.org/root for details", "Using version dev-master for islandora-rdm/islandora_fits", "./composer.json has been updated", "> DrupalProject\\composer\\ScriptHandler::checkComposerVersion", "Loading composer repositories with package information", "Updating dependencies (including require-dev)", "Package operations: 0 installs, 1 update, 0 removals", "  - Updating islandora-rdm/islandora_fits dev-master (b8a126e => 106ed01): ", "Installation failed, reverting ./composer.json to its original content.", "", "                                                                                                    ", "  [RuntimeException]                                                                                ", "  Source directory web/modules/contrib/islandora_fits has unpushed changes on the current branch:   ", "  M\tconfig/install/field.storage.media.fits_ois_file_information_md5che.yml                         ", "  A\tislandora_fits.links.menu.yml                                                                   ", "  M\tislandora_fits.module                                                                           ", "  A\tislandora_fits.routing.yml                                                                      ", "  A\tsrc/Controller/IslandoraFitsDerivativeController.php                                            ", "  A\tsrc/Form/AdminForm.php                                                                          ", "  M\tsrc/Plugin/Action/GenerateFitsDerivative.php                                                    ", "  A\tsrc/Plugin/Action/GenerateFitsDerivativeFile.php                                                ", "  M\tsrc/Services/XMLTransform.php                                                                   ", "  M\ttemplates/fits.html.twig                                                                        ", "                                                                                                    ", "", "require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...", ""]}


```

**Comment by dannylamb** [comment]
This is no longer needed.

**Pull request closed without merging**
