### PR TITLE
External content and triplestore indexing fix

### PR DESCRIPTION
**Pull request by dannylamb**
Part of https://github.com/Islandora-CLAW/CLAW/issues/1079

This PR will build Alpaca from source and deploy all the karaf stuff through the Alpaca role to get Fedora triplestore indexing working again with Fedora 5.0.  This PR temporarily disables the Apix role, which I'll put back once Apix is brought into line as well.

This PR also pulls in a new fcrepo role which templates out the config neccessary for external content.  This fixes how Media is indexed in fedora.

## Testing Instructions
- Pull down this PR
- `rm -rf roles/external`
- `vagrant up`
- Make a Repository Item, tag it as 'Image', and then add an 'Original File' media to it.
- Go check Gemini, you should now see all files in Gemini, regardless if they're in Fedora or not.  You also _should not_ see media at all in Gemini.  Just files, from which the rdf can be found with a HEAD request.
```bash
mysql> select drupal_uri, fedora_uri from Gemini;
+---------------------------------------------------------------------------+------------------------------------------------------------------------------------+
| drupal_uri                                                                | fedora_uri                                                                         |
+---------------------------------------------------------------------------+------------------------------------------------------------------------------------+
| http://localhost:8000/taxonomy/term/5?_format=jsonld                      | http://localhost:8080/fcrepo/rest/00/84/25/19/00842519-a0ab-41d1-9a0a-748fe226cf9c |
| http://localhost:8000/taxonomy/term/1?_format=jsonld                      | http://localhost:8080/fcrepo/rest/0e/8f/24/56/0e8f2456-445e-4977-ba27-271124d616c6 |
| http://localhost:8000/taxonomy/term/2?_format=jsonld                      | http://localhost:8080/fcrepo/rest/0f/20/d6/a1/0f20d6a1-4d52-44de-bf73-a7fb7f84051e |
| http://localhost:8000/taxonomy/term/16?_format=jsonld                     | http://localhost:8080/fcrepo/rest/18/69/80/05/18698005-c031-4ed6-bbc8-0ff8b4992b61 |
| http://localhost:8000/taxonomy/term/14?_format=jsonld                     | http://localhost:8080/fcrepo/rest/27/05/5a/cf/27055acf-d5c3-4cdd-9615-a18f5ca82e30 |
| http://localhost:8000/taxonomy/term/6?_format=jsonld                      | http://localhost:8080/fcrepo/rest/2e/34/90/74/2e349074-a1f1-4aaa-beb4-4e0a15feb6b9 |
| http://localhost:8000/taxonomy/term/25?_format=jsonld                     | http://localhost:8080/fcrepo/rest/2e/71/f0/42/2e71f042-51f3-4f05-8b65-ed2be04f0225 |
| http://localhost:8000/taxonomy/term/24?_format=jsonld                     | http://localhost:8080/fcrepo/rest/34/17/9c/96/34179c96-2b41-422b-9a88-a8754a677213 |
| http://localhost:8000/_flysystem/fedora/2019-04/Arrival-Back-Home.jpg     | http://localhost:8080/fcrepo/rest/2019-04/Arrival-Back-Home.jpg                    |
| http://localhost:8000/taxonomy/term/20?_format=jsonld                     | http://localhost:8080/fcrepo/rest/54/d3/f0/6e/54d3f06e-b9ac-4caf-9d2b-e6bc61189529 |
| http://localhost:8000/node/1?_format=jsonld                               | http://localhost:8080/fcrepo/rest/68/4f/ab/a4/684faba4-9cda-4ce1-9bbf-92d0c2cab2fc |
| http://localhost:8000/taxonomy/term/17?_format=jsonld                     | http://localhost:8080/fcrepo/rest/76/63/26/17/76632617-37d4-421e-bb0e-732b42ccdcc4 |
| http://localhost:8000/taxonomy/term/22?_format=jsonld                     | http://localhost:8080/fcrepo/rest/7d/a1/d7/62/7da1d762-b3c4-41a8-879d-06a741b084cd |
| http://localhost:8000/taxonomy/term/9?_format=jsonld                      | http://localhost:8080/fcrepo/rest/8b/30/ba/21/8b30ba21-a2b0-452b-9d1c-d8ce4fb57cca |
| http://localhost:8000/sites/default/files/2019-04/1-Service%20File.jpg    | http://localhost:8080/fcrepo/rest/96/b2/67/23/96b26723-b08e-4c71-b38f-c818a5e6f3f1 |
| http://localhost:8000/sites/default/files/2019-04/1-Thumbnail%20Image.jpg | http://localhost:8080/fcrepo/rest/a2/0d/cc/b2/a20dccb2-a1b3-41da-abce-90132a096213 |
| http://localhost:8000/taxonomy/term/19?_format=jsonld                     | http://localhost:8080/fcrepo/rest/a3/53/e5/0c/a353e50c-24e5-4d1d-8a0c-2921aa98095a |
| http://localhost:8000/taxonomy/term/10?_format=jsonld                     | http://localhost:8080/fcrepo/rest/a7/d8/79/57/a7d87957-69d5-44dc-ac54-80ada17bb137 |
| http://localhost:8000/taxonomy/term/21?_format=jsonld                     | http://localhost:8080/fcrepo/rest/b2/5e/c8/48/b25ec848-5058-4be1-8ef1-857cdb63f0f0 |
| http://localhost:8000/taxonomy/term/7?_format=jsonld                      | http://localhost:8080/fcrepo/rest/be/45/81/1f/be45811f-fe32-4dc6-979e-e2badb04f69c |
| http://localhost:8000/taxonomy/term/15?_format=jsonld                     | http://localhost:8080/fcrepo/rest/cc/45/4d/c0/cc454dc0-3f43-4df9-a89b-024eb0cb8e33 |
| http://localhost:8000/taxonomy/term/4?_format=jsonld                      | http://localhost:8080/fcrepo/rest/d2/6b/95/55/d26b9555-7177-4050-8b46-a0b211a68e88 |
| http://localhost:8000/taxonomy/term/3?_format=jsonld                      | http://localhost:8080/fcrepo/rest/d9/24/5c/78/d9245c78-dc91-4eaa-9704-5c74b9a4e07b |
| http://localhost:8000/taxonomy/term/18?_format=jsonld                     | http://localhost:8080/fcrepo/rest/dc/7e/02/10/dc7e0210-dfe1-4660-85c4-53fe0c75cb18 |
| http://localhost:8000/taxonomy/term/11?_format=jsonld                     | http://localhost:8080/fcrepo/rest/e6/63/1f/61/e6631f61-a56e-4d83-beb1-b9d9d84c3561 |
| http://localhost:8000/taxonomy/term/13?_format=jsonld                     | http://localhost:8080/fcrepo/rest/ee/84/c3/d1/ee84c3d1-462b-4b68-8610-7841d74defad |
| http://localhost:8000/taxonomy/term/12?_format=jsonld                     | http://localhost:8080/fcrepo/rest/f5/90/31/51/f5903151-9324-46b7-8cc2-d1e07d69ec59 |
| http://localhost:8000/taxonomy/term/8?_format=jsonld                      | http://localhost:8080/fcrepo/rest/fd/bc/90/04/fdbc9004-cd94-40d8-a199-606bd67db7e6 |
| http://localhost:8000/taxonomy/term/23?_format=jsonld                     | http://localhost:8080/fcrepo/rest/ff/1b/82/7e/ff1b827e-f153-4939-b860-dbe866b3f464 |
+---------------------------------------------------------------------------+------------------------------------------------------------------------------------+
29 rows in set (0.00 sec)
```
- HEAD the Original File, which is contained within Fedora.  You should get a 200 OK response.  You can get the url for the file's RDF with the `rel="describedby"` link header.
```bash
vagrant@claw:/var/www/html/Crayfish$ curl -I http://localhost:8080/fcrepo/rest/2019-04/Arrival-Back-Home.jpg
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Cache-Control: private
Expires: Thu, 01 Jan 1970 00:00:00 UTC
Set-Cookie: JSESSIONID=89EA5154319CC643EC7D7403EFDCA0AF; Path=/fcrepo/; HttpOnly
Set-Cookie: rememberMe=deleteMe; Path=/fcrepo; Max-Age=0; Expires=Sun, 28-Apr-2019 18:44:19 GMT
ETag: "bd9c7c8b6f4f486501c6eb01e978240c865b3712"
Last-Modified: Mon, 29 Apr 2019 14:15:01 GMT
Accept-Ranges: bytes
Content-Disposition: attachment; filename=""; creation-date="Mon, 29 Apr 2019 14:15:01 GMT"; modification-date="Mon, 29 Apr 2019 14:15:01 GMT"; size=3166278
Link: <http://www.w3.org/ns/ldp#Resource>;rel="type"
Link: <http://www.w3.org/ns/ldp#NonRDFSource>;rel="type"
Link: <http://localhost:8080/fcrepo/rest/2019-04/Arrival-Back-Home.jpg/fcr:metadata>; rel="describedby"
Link: <http://localhost:8080/fcrepo/rest/2019-04/Arrival-Back-Home.jpg>; rel="timegate"
Link: <http://localhost:8080/fcrepo/rest/2019-04/Arrival-Back-Home.jpg>; rel="original"
Link: <http://localhost:8080/fcrepo/rest/2019-04/Arrival-Back-Home.jpg/fcr:versions>; rel="timemap"
Link: <http://mementoweb.org/ns#OriginalResource>; rel="type"
Link: <http://mementoweb.org/ns#TimeGate>; rel="type"
Accept-External-Content-Handling: copy,redirect,proxy
Allow: DELETE,HEAD,GET,PUT,OPTIONS
Link: <http://localhost:8080/fcrepo/rest/2019-04/Arrival-Back-Home.jpg/fcr:acl>; rel="acl"
Content-Type: image/jpeg
Content-Length: 3166278
Date: Mon, 29 Apr 2019 18:44:19 GMT
```
- Get its RDF and it should be populated correctly (before only system metadata from fcrepo was there, and nothing from Drupal was making it over).
```bash
vagrant@claw:/var/www/html/Crayfish$ curl http://localhost:8080/fcrepo/rest/2019-04/Arrival-Back-Home.jpg/fcr:metadata
@prefix premis:  <http://www.loc.gov/premis/rdf/v1#> .
@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix fedora:  <http://fedora.info/definitions/v4/repository#> .
@prefix ebucore:  <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#> .
@prefix ldp:  <http://www.w3.org/ns/ldp#> .
@prefix dcterms:  <http://purl.org/dc/terms/> .
@prefix iana:  <http://www.iana.org/assignments/relation/> .

<http://localhost:8080/fcrepo/rest/2019-04/Arrival-Back-Home.jpg>
        rdf:type                    fedora:NonRdfSourceDescription ;
        rdf:type                    <http://pcdm.org/models#File> ;
        rdf:type                    <http://pcdm.org/use#OriginalFile> ;
        rdf:type                    fedora:Binary ;
        rdf:type                    fedora:Resource ;
        fedora:lastModifiedBy       "bypassAdmin" ;
        <http://schema.org/dateModified>  "2019-04-29T14:15:13+00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        <http://schema.org/author>  <http://localhost:8000/user/1?_format=jsonld> ;
        <http://schema.org/sameAs>  "http://localhost:8000/_flysystem/fedora/2019-04/Arrival-Back-Home.jpg" ;
        <http://schema.org/dateCreated>  "2019-04-29T14:14:55+00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        ebucore:width               "2200"^^<http://www.w3.org/2001/XMLSchema#int> ;
        premis:hasSize              "3166278"^^<http://www.w3.org/2001/XMLSchema#long> ;
        ebucore:hasMimeType         "image/jpeg" ;
        fedora:createdBy            "bypassAdmin" ;
        fedora:created              "2019-04-29T14:15:01.808Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        fedora:lastModified         "2019-04-29T14:15:19.664Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        premis:hasMessageDigest     <urn:sha1:aaa5b588e151eca37aa5f7cc7462702abae2d3b3> ;
        ebucore:height              "1616"^^<http://www.w3.org/2001/XMLSchema#int> ;
        <http://pcdm.org/models#fileOf>  <http://localhost:8000/node/1?_format=jsonld> ;
        rdf:label                   "Arrival"@en ;
        ebucore:filename            "" ;
        dcterms:title               "Arrival"@en ;
        rdf:type                    ldp:NonRDFSource ;
        iana:describedby            <http://localhost:8080/fcrepo/rest/2019-04/Arrival-Back-Home.jpg/fcr:metadata> ;
        fedora:hasFixityService     <http://localhost:8080/fcrepo/rest/2019-04/Arrival-Back-Home.jpg/fcr:fixity> .

```

- Then HEAD a file that's 'external content' in Fedora (either the service file or thumbnail).  You should see a 307 Redirect status code (external content is set up to use Redirect for now):
```bash
vagrant@claw:/var/www/html/Crayfish$ curl -I http://localhost:8080/fcrepo/rest/96/b2/67/23/96b26723-b08e-4c71-b38f-c818a5e6f3f1
HTTP/1.1 307 Temporary Redirect
Server: Apache-Coyote/1.1
Cache-Control: private
Expires: Thu, 01 Jan 1970 00:00:00 UTC
Set-Cookie: JSESSIONID=87200D0E58A3168EB00D086E01E139BA; Path=/fcrepo/; HttpOnly
Set-Cookie: rememberMe=deleteMe; Path=/fcrepo; Max-Age=0; Expires=Sun, 28-Apr-2019 18:43:48 GMT
ETag: "b9c2fd2a5e872a2e74ea67daa88f20226d28fa21"
Last-Modified: Mon, 29 Apr 2019 14:15:21 GMT
Accept-Ranges: bytes
Content-Disposition: attachment; filename=""; creation-date="Mon, 29 Apr 2019 14:15:21 GMT"; modification-date="Mon, 29 Apr 2019 14:15:21 GMT"; size=3271893
Link: <http://www.w3.org/ns/ldp#Resource>;rel="type"
Link: <http://www.w3.org/ns/ldp#NonRDFSource>;rel="type"
Link: <http://localhost:8080/fcrepo/rest/96/b2/67/23/96b26723-b08e-4c71-b38f-c818a5e6f3f1/fcr:metadata>; rel="describedby"
Link: <http://localhost:8080/fcrepo/rest/96/b2/67/23/96b26723-b08e-4c71-b38f-c818a5e6f3f1>; rel="timegate"
Link: <http://localhost:8080/fcrepo/rest/96/b2/67/23/96b26723-b08e-4c71-b38f-c818a5e6f3f1>; rel="original"
Link: <http://localhost:8080/fcrepo/rest/96/b2/67/23/96b26723-b08e-4c71-b38f-c818a5e6f3f1/fcr:versions>; rel="timemap"
Link: <http://mementoweb.org/ns#OriginalResource>; rel="type"
Link: <http://mementoweb.org/ns#TimeGate>; rel="type"
Accept-External-Content-Handling: copy,redirect,proxy
Allow: DELETE,HEAD,GET,PUT,OPTIONS
Link: <http://localhost:8080/fcrepo/rest/96/b2/67/23/96b26723-b08e-4c71-b38f-c818a5e6f3f1/fcr:acl>; rel="acl"
Content-Location: http://localhost:8000/sites/default/files/2019-04/1-Service%20File.jpg
Location: http://localhost:8000/sites/default/files/2019-04/1-Service%20File.jpg
Content-Type: image/jpeg
Content-Length: 0
Date: Mon, 29 Apr 2019 18:43:48 GMT
```

- And get its RDF using the `rel="describedby"` link header
```bash
vagrant@claw:/var/www/html/Crayfish$ curl http://localhost:8080/fcrepo/rest/96/b2/67/23/96b26723-b08e-4c71-b38f-c818a5e6f3f1/fcr:metadata
@prefix premis:  <http://www.loc.gov/premis/rdf/v1#> .
@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix fedora:  <http://fedora.info/definitions/v4/repository#> .
@prefix ebucore:  <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#> .
@prefix ldp:  <http://www.w3.org/ns/ldp#> .
@prefix dcterms:  <http://purl.org/dc/terms/> .
@prefix iana:  <http://www.iana.org/assignments/relation/> .

<http://localhost:8080/fcrepo/rest/96/b2/67/23/96b26723-b08e-4c71-b38f-c818a5e6f3f1>
        rdf:type                    fedora:NonRdfSourceDescription ;
        rdf:type                    <http://pcdm.org/models#File> ;
        rdf:type                    <http://pcdm.org/use#ServiceFile> ;
        rdf:type                    fedora:Binary ;
        rdf:type                    fedora:Resource ;
        fedora:lastModifiedBy       "bypassAdmin" ;
        <http://schema.org/dateModified>  "2019-04-29T14:15:20+00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        <http://schema.org/author>  <http://localhost:8000/user/1?_format=jsonld> ;
        <http://schema.org/sameAs>  "http://localhost:8000/sites/default/files/2019-04/1-Service%20File.jpg" ;
        <http://schema.org/dateCreated>  "2019-04-29T14:15:20+00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        ebucore:width               "2200"^^<http://www.w3.org/2001/XMLSchema#int> ;
        premis:hasSize              "3271893"^^<http://www.w3.org/2001/XMLSchema#long> ;
        ebucore:hasMimeType         "image/jpeg" ;
        fedora:createdBy            "bypassAdmin" ;
        fedora:created              "2019-04-29T14:15:21.69Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        fedora:lastModified         "2019-04-29T14:15:23.344Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        ebucore:height              "1616"^^<http://www.w3.org/2001/XMLSchema#int> ;
        <http://pcdm.org/models#fileOf>  <http://localhost:8000/node/1?_format=jsonld> ;
        rdf:label                   "1-Service File.jpg"@en ;
        ebucore:filename            "" ;
        dcterms:title               "1-Service File.jpg"@en ;
        rdf:type                    ldp:NonRDFSource ;
        iana:describedby            <http://localhost:8080/fcrepo/rest/96/b2/67/23/96b26723-b08e-4c71-b38f-c818a5e6f3f1/fcr:metadata> ;
        fedora:hasFixityService     <http://localhost:8080/fcrepo/rest/96/b2/67/23/96b26723-b08e-4c71-b38f-c818a5e6f3f1/fcr:fixity> .
```
And it should also look like it's got all the info from Drupal!

Then go check the triplestore.  You should have all those triples from BOTH Fedora and Drupal in there:
```
SELECT ?s ?p ?o WHERE { <http://localhost:8080/fcrepo/rest/2019-04/Arrival-Back-Home.jpg> ?p ?o }
```
AND
```
SELECT ?s ?p ?o WHERE { <http://localhost:8000/media/1?_format=jsonld> ?p ?o }
```
should return mostly the same triples, with Fedora having a few extra indexed than Drupal because of extra Fedora specific metadata.

### CODE REVIEW

**Comment by Natkeeran** [comment]
@dannylamb 

How exactly do we test this?

**Comment by dannylamb** [comment]
@Natkeeran I've got to make some updates for the fcrepo role, and then I'll post up how I'm testing it once I can confirm that this still works.

**Comment by dannylamb** [comment]
@Natkeeran Updated test instructions in the initial message

**Comment by dannylamb** [comment]
OK, so after review, we'll have to slice new versions of Crayfish and Alpaca, then bump the versions in their roles.  Then update requirements.yml to point to those official roles instead of branches.  Then I can clear out the stuff to build from source for Alpaca.

Then once the `islandora` and `islandora demo PRs` are meregd I can clear out some composer.json shenanigans in `islandora_demo`.

Then this can get merged :tada:

**Comment by seth-shaw-unlv** [comment]
I started this PR up ~22 minutes ago and it just failed on tomcat:
```
TASK [Islandora-Devops.tomcat8 : template /opt/tomcat/bin/setenv.sh] ***********
Monday 29 April 2019  13:24:25 -0700 (0:00:00.040)       0:21:54.887 ********** 
fatal: [default]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'fcrepo_allowed_external_content_file' is undefined"}
```

**Comment by dannylamb** [comment]
Ah, did you blow up roles/external? I should probably add that to the
testing instructions.

**Comment by seth-shaw-unlv** [comment]
@dannylamb, I realized that I hadn't wiped roles/external afterward. Anyway, I have a new problem, this time with adding Alpaca features (specifically fcrepo-service-activemq and fcrepo-indexing-triplestore):
```
TASK [Islandora-Devops.alpaca : Add Alpaca Features] ***************************
Monday 29 April 2019  16:17:40 -0700 (0:00:00.048)       0:30:38.783 ********** 
failed: [default] (item=fcrepo-service-activemq) => {"changed": false, "item": "fcrepo-service-activemq", "msg": "client: Ignoring predefined value for KARAF_HOME\nError executing command: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=fcrepo-service-activemq; type=karaf.feature; version=\"[5.0.0,5.0.0]\"; filter:=\"(&(osgi.identity=fcrepo-service-activemq)(type=karaf.feature)(version>=5.0.0)(version<=5.0.0))\" [caused by: Unable to resolve fcrepo-service-activemq/5.0.0: missing requirement [fcrepo-service-activemq/5.0.0] osgi.identity; osgi.identity=activemq-camel; type=karaf.feature; version=\"[5.14.0,6.0.0)\"]\n"}
changed: [default] => (item=fcrepo-camel)
changed: [default] => (item=fcrepo-service-camel)
failed: [default] (item=fcrepo-indexing-triplestore) => {"changed": false, "item": "fcrepo-indexing-triplestore", "msg": "client: Ignoring predefined value for KARAF_HOME\nError executing command: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=fcrepo-indexing-triplestore; type=karaf.feature; version=\"[5.0.0,5.0.0]\"; filter:=\"(&(osgi.identity=fcrepo-indexing-triplestore)(type=karaf.feature)(version>=5.0.0)(version<=5.0.0))\" [caused by: Unable to resolve fcrepo-indexing-triplestore/5.0.0: missing requirement [fcrepo-indexing-triplestore/5.0.0] osgi.identity; osgi.identity=org.fcrepo.camel.fcrepo-indexing-triplestore-blueprint; type=osgi.bundle; version=\"[5.0.0,5.0.0]\"; resolution:=mandatory [caused by: Unable to resolve org.fcrepo.camel.fcrepo-indexing-triplestore-blueprint/5.0.0: missing requirement [org.fcrepo.camel.fcrepo-indexing-triplestore-blueprint/5.0.0] osgi.service; effective:=active; filter:=\"(&(objectClass=org.apache.camel.Component)(osgi.jndi.service.name=fcrepo/Broker))\"]]\n"}
changed: [default] => (item=islandora-http-client)
changed: [default] => (item=islandora-indexing-triplestore)
changed: [default] => (item=islandora-indexing-fcrepo)
changed: [default] => (item=islandora-connector-derivative)
```

**Comment by whikloj** [comment]
I have had some different errors, but the last build produced the same as @seth-shaw-unlv

**Comment by dannylamb** [comment]
I had some missing things I forgot to push up that were cached in my `roles/external`.  This should work now.

**Comment by dannylamb** [comment]
@seth-shaw-unlv OK, one last `vagrant up` to test.  I think we've merged everything in, sliced all appropriate versions, and updated all references in the playbook.  Here's hoping :wave: :game_die: :

**Comment by dannylamb** [comment]
...almost forgot to wipe `roles/external`!

**Comment by seth-shaw-unlv** [comment]
Build succeeds, media indexed as expected. Nice work everyone!

**Pull request merged**
