### PR TITLE
Install PHP 7.1

### PR DESCRIPTION
**Pull request by whikloj**
Resolves: https://github.com/Islandora-CLAW/CLAW/issues/1007

Based on @kayakr's work [in that issue](https://github.com/Islandora-CLAW/CLAW/issues/1007#issuecomment-460475411)

I tried to get a single location to add/edit the `php_version` but it keep missing it and defaulting to PHP 7.2. 

If anyone has a suggestion please let me know, but Ansible variables are the stuff of nightmares. 

I have tested it in Ubuntu and Centos and it seems to work.

Once this is confirmed we should also update the composer.lock files for the Crayfish microservices and Crayfish-Commons as well.

### CODE REVIEW

**Comment by whikloj** [comment]
@kayakr not sure why it worked for me, but I'll wrap it.

**Comment by kayakr** [comment]
fwiw, this works fine for me.

**Comment by dannylamb** [comment]
I can confirm Ubuntu is good to go.  Testing CENTOS now.

**Comment by dannylamb** [comment]
Hrm... oddly, changing ISLANDORA_DISTRO in the Vagrantfile to centos/7 fails and running `vagrant up` fails, but `$ ISLANDORA_DISTRO="centos/7" vagrant up` works just fine.  Anyway, serves me right not to read the README when trying Centos (I prefer Ubuntu).

Anyway, from Cent:
```bash
daniel@daniel-Latitude-3560:~/Code/Environments/claw-playbook$ vagrant ssh
Last login: Fri Feb  8 18:41:08 2019 from 10.0.2.2
[vagrant@claw ~]$ php --version
PHP 7.1.26 (cli) (built: Jan  9 2019 08:02:33) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
```

**Pull request merged**
