### PR TITLE
Use external roles

### PR DESCRIPTION
**Pull request by whikloj**
Resolves https://github.com/Islandora-CLAW/CLAW/issues/764

This moves all the internal roles out to the external ones.

This has introduced a bug [documented here](https://github.com/Islandora-CLAW/CLAW/issues/764#issuecomment-353077532) where you (or at least I) can't download all the external roles without a failure from galaxy (or Github...which is my guess).

### How To Test
1. Clone this branch to a new directory.
2. Run `vagrant up`. It will fail (or it always does for me on the 21st role)
3. Run `vagrant provision`

You should have a working CLAW instance.

### CODE REVIEW

**Comment by dannylamb** [comment]
`vagrant up`

Let's see what happens.

**Comment by dannylamb** [comment]
:confused: Hrm... I just made it past `ansible-galaxy` unscathed and didn't have to force provisioning.  I'll let you know when it's totally done if it's fine.

**Comment by whikloj** [comment]
Did you delete your roles/external directory? 

If not then you didn't have to re-download all of the geerlingguy roles and you only downloaded our 6 new roles. Hence not hitting the 21 limit.

**Comment by dannylamb** [comment]
Ah, ok.  Let me try that.

**Comment by dannylamb** [comment]
:man_shrugging: I dunno, just tried it twice, clobbering `roles/external` and it worked fine both times.

**Comment by whikloj** [comment]
What dark pact did you make?!?!!?!

**Comment by dannylamb** [comment]
Me and Beezlebot go way back.


But it's probably just my ultra-slow internet.

**Comment by Natkeeran** [comment]
Not sure if this is directly related to this PR.  But, running into this error while vagrant up.
```
TASK [webserver-app : Install config] ******************************************
Wednesday 03 January 2018  16:13:52 -0500 (0:00:00.551)       0:03:25.182 ***** 
fatal: [default]: FAILED! => {"changed": true, "cmd": ["drush", "config-import", "-y", "--partial", "--source=/opt/islandora/configs/drupal"], "delta": "0:00:00.318638", "end": "2018-01-03 21:13:53.570524", "failed": true, "rc": 1, "start": "2018-01-03 21:13:53.251886", "stderr": "Drupal\\Core\\Config\\ConfigImporterException: There were errors        \u001b[31;40m\u001b[1m[error]\u001b[0m\nvalidating the config synchronization. in\nDrupal\\Core\\Config\\ConfigImporter->validate() (line 728 of\n/var/www/html/drupal/web/core/lib/Drupal/Core/Config/ConfigImporter.php).\nThe import failed due for the following reasons:                     \u001b[31;40m\u001b[1m[error]\u001b[0m\nConfiguration <em class=\"placeholder\">filehash.settings</em> depends\non the <em class=\"placeholder\">File hash</em> module that will not be\ninstalled after import.\nConfiguration <em class=\"placeholder\">rest.resource.entity.media</em>\ndepends on the <em class=\"placeholder\">RESTful Web Services</em>\nmodule that will not be installed after import.\nConfiguration <em class=\"placeholder\">rest.resource.entity.node</em>\ndepends on the <em class=\"placeholder\">RESTful Web Services</em>\nmodule that will not be installed after import.", "stderr_lines": ["Drupal\\Core\\Config\\ConfigImporterException: There were errors        \u001b[31;40m\u001b[1m[error]\u001b[0m", "validating the config synchronization. in", "Drupal\\Core\\Config\\ConfigImporter->validate() (line 728 of", "/var/www/html/drupal/web/core/lib/Drupal/Core/Config/ConfigImporter.php).", "The import failed due for the following reasons:                     \u001b[31;40m\u001b[1m[error]\u001b[0m", "Configuration <em class=\"placeholder\">filehash.settings</em> depends", "on the <em class=\"placeholder\">File hash</em> module that will not be", "installed after import.", "Configuration <em class=\"placeholder\">rest.resource.entity.media</em>", "depends on the <em class=\"placeholder\">RESTful Web Services</em>", "module that will not be installed after import.", "Configuration <em class=\"placeholder\">rest.resource.entity.node</em>", "depends on the <em class=\"placeholder\">RESTful Web Services</em>", "module that will not be installed after import."], "stdout": " Collection  Config                                    Operation                \n             rest.resource.entity.node                 \u001b[1;32;40m\u001b[1mcreate\u001b[0m \n             rest.resource.entity.media                \u001b[1;32;40m\u001b[1mcreate\u001b[0m \n             block.block.views_block__membership_view  \u001b[1;32;40m\u001b[1mcreate\u001b[0m \n             _block_1                                                           \n             filehash.settings                         \u001b[1;32;40m\u001b[1mcreate\u001b[0m\nImport the listed configuration changes? (y/n): y", "stdout_lines": [" Collection  Config                                    Operation                ", "             rest.resource.entity.node                 \u001b[1;32;40m\u001b[1mcreate\u001b[0m ", "             rest.resource.entity.media                \u001b[1;32;40m\u001b[1mcreate\u001b[0m ", "             block.block.views_block__membership_view  \u001b[1;32;40m\u001b[1mcreate\u001b[0m ", "             _block_1                                                           ", "             filehash.settings                         \u001b[1;32;40m\u001b[1mcreate\u001b[0m", "Import the listed configuration changes? (y/n): y"]}
```

**Comment by Natkeeran** [comment]
Please ignore my previous comment.  vagrant up works with this PR.  No errors.

**Comment by dannylamb** [comment]
Are we cool to move this in, then?

**Comment by Natkeeran** [comment]
@dannylamb Yes, Works as expected for me.

**Comment by dannylamb** [comment]
@whikloj @Natkeeran @seth-shaw-unlv Ok, before this goes in then, let's take a look at what we've got going and see if there's other stuff we can sneak in first before I unleash some git-fu on all the repositories for the split out roles.

**Comment by whikloj** [comment]
Wait?! What git-fu are your doing? 

The plan (as I understood it) was to NOT do anything to claw-playbook until we got this merged and the external roles in use. Then I was going to start on PRs to clean up all the variable overlap that was happening in the various roles.

**Comment by whikloj** [comment]
So any PRs for the individual roles could be recreated on their specific repository (ie #44), but then it would be easier to test as we would actually be using the external roles here.

**Comment by Natkeeran** [comment]
@whikloj Yes, that approach seems good to me.

**Comment by dannylamb** [comment]
I was totally going to just force push whatever changes have already rolled through to the individual repos and merge the PR after testing again.  Just sense it's stuff we've already reviewed.  Subsequent work would still go through the normal workflow for the applicable role(s).

**Comment by whikloj** [comment]
@dannylamb But you shouldn't need to force push anything. I rebuilt all the external role repositories as exact copies of what is currently in claw-playbook (I had to add the `meta/main.yml` to some). But otherwise this PR should merge without any issues and once that happens we are moved to using external roles.

**Comment by jonathangreen** [comment]
Just going to throw this here to tie the two discussions together. I can't get the roles to come in cleanly, same error as Jared had. I made a PR on his PR here: https://github.com/whikloj/claw-playbook/pull/1 that pulls them from git instead of galaxy and that works okay for me. I dunno if thats an okay solution for everyone.

**Comment by jonathangreen** [comment]
So this comes up fine for me after two things: 
1) switching to git for some roles: https://github.com/whikloj/claw-playbook/pull/1
2) commenting out FITS: https://github.com/Islandora-CLAW/CLAW/issues/747
  - I can make a PR to address this one.

**Comment by whikloj** [comment]
I'm going to have to rebase this PR after the FITS removal, so do we have any issues with switching the galaxy roles to Github repos?

If we don't I can merge @jonathangreen's PR.

Personally I'm a little concerned about the fact that Galaxy seems to be our failure point.

**Comment by whikloj** [comment]
@dannylamb I just went ahead and merged @jonathangreen's PR. It solves the problem for him and me (maybe a OSX issue) and now we are good to go.

**Comment by Natkeeran** [comment]
@dannylamb Can we merge this one!

**Pull request merged**
