### PR TITLE
Do migrations tagwise for the starter site.

### PR DESCRIPTION
**Pull request by adam-vessey**
**GitHub Issue**: (link)

* Other Relevant Links (Google Groups discussion, related pull requests,
 Release pull requests, etc.)

# What does this Pull Request do?

A brief description of what the intended result of the PR will be and/or what
 problem it solves.

# What's new?
A in-depth description of the changes made by this PR. Technical details and
 possible side effects.

* Changes x feature to such that y
* Added x
* Removed y
* Does this change require documentation to be updated? 
* Does this change add any new dependencies? 
* Does this change require any other modifications to be made to the repository
 (i.e. Regeneration activity, etc.)? 
* Could this change impact execution of existing code?

# How should this be tested?

A description of what steps someone could take to:
* Reproduce the problem you are fixing (if applicable)
* Test that the Pull Request does what is intended.
* Please be as detailed as possible.
* Good testing instructions help get your PR completed faster.

# Additional Notes:
Any additional information that you think would be helpful when reviewing this
 PR.

# Interested parties
Tag (@ mention) interested parties or, if unsure, @Islandora-Devops/committers

### CODE REVIEW

**Comment by rosiel** [comment]
It seems like it's jumping through hoops to preserve a very edge (if not absurd) use case - where you'd deliberately install islandora_fits  but then choose to not do the migration. Is there an argument that this behaviour is worth preserving? (or is this to prevent any changes to the expected behaviour/interface that might be used in workflows?)

**Comment by adam-vessey** [comment]
@rosiel : Not quite? The `demo` thing doesn't (or didn't?) do FITS: https://github.com/Islandora-Devops/islandora-playbook/blob/dev/vars/demo.yml ... so to avoid attempting to execute a migration in an environment that didn't have it, a variable was introduced. Now, similar kind of thing, where the `--tag=islandora` is only valid if the migrations bear the tag, which is unknown in the `demo` environment.

**Comment by rosiel** [comment]
Tested and works on `starter_dev`. 

I'm struggling to test on `demo` because of PHP conflicts, and the fact that we're possibly using the wrong branch of islandora_sandbox... but that's far beyond this ticket.

I'd say this ticket is ready to go. @adam-vessey any other concerns before taking it out of draft?

**Comment by adam-vessey** [comment]
Nah, my only concern is that I hadn't actually run things myself... theoretical code was theoretical. :P 

If it is indeed functional, then sure, let's do it!

**Comment by rosiel** [comment]
Tested and works on `starter_dev`. 

I'm struggling to test on `demo` - finally it ran, but some [other issues](https://github.com/Islandora-Devops/islandora-playbook/pull/255#issuecomment-1452137967) popped up that are breaking demo anyway. 

I'd say this ticket is ready to go. @adam-vessey any other concerns before taking it out of draft?

**Review by rosiel — APPROVED** [review]

**Pull request merged**
