### PR TITLE
Bumping crayfish role in requirements.yml

### PR DESCRIPTION
**Pull request by dannylamb**
Part of https://github.com/Islandora-CLAW/CLAW/issues/929

### CODE REVIEW

**Comment by dannylamb** [comment]
@Natkeeran ^^

**Comment by Natkeeran** [comment]
@dannylamb 

Something does not look right.  It did not pull the Homarus stuff.  Will check this tomorrow.

**Comment by Natkeeran** [comment]
@dannylamb you need bump the version to 0.0.6.

**Comment by dannylamb** [comment]
@Natkeeran :man_facepalming: bumped

**Pull request merged**
