### PR TITLE
Issue 640

### PR DESCRIPTION
**Pull request by dannylamb**
Resolves: Islandora-CLAW/CLAW#640

## Testing instructions
This PR assumes on the other PRs for Islandora-CLAW/CLAW#640 have been merged in and are available through composer / maven.  So to test, we need to set it up to build from source and pull from my branches for Crayfish and Alpaca.  To do so, scrape out the following patch file and apply it to your claw-playbook clone.
```diff
diff --git a/inventory/vagrant/group_vars/webserver/drupal.yml b/inventory/vagrant/group_vars/webserver/drupal.yml
index 09f7e9d..5edca07 100644
--- a/inventory/vagrant/group_vars/webserver/drupal.yml
+++ b/inventory/vagrant/group_vars/webserver/drupal.yml
@@ -12,6 +12,7 @@ drupal_composer_dependencies:
   - "drupal/media_entity_image:^1.2"
   - "drupal/search_api_solr:1.0.0"
   - "drupal/facets:1.x-dev"
+  - "drupal/filehash:^1.1"
   - "islandora/carapace:dev-8.x-1.x"
   - "islandora/islandora_image:dev-8.x-1.x"
 drupal_composer_project_package: "drupal-composer/drupal-project:8.x-dev"
@@ -41,6 +42,7 @@ drupal_enable_modules:
   - devel
   - search_api
   - carapace
+  - filehash
   - islandora_image
 drupal_trusted_hosts:
   - ^localhost$
diff --git a/roles/internal/alpaca/defaults/main.yml b/roles/internal/alpaca/defaults/main.yml
index 6848277..988b184 100644
--- a/roles/internal/alpaca/defaults/main.yml
+++ b/roles/internal/alpaca/defaults/main.yml
@@ -1,8 +1,8 @@
 ---
 
-alpaca_from_source: no
+alpaca_from_source: yes
 
-alpaca_version: master
+alpaca_version: issue-640
 alpaca_clone_directory: /opt/alpaca
 
 alpaca_karaf_repos:
diff --git a/roles/internal/alpaca/tasks/compile.yml b/roles/internal/alpaca/tasks/compile.yml
index 30507d4..fcc66fb 100644
--- a/roles/internal/alpaca/tasks/compile.yml
+++ b/roles/internal/alpaca/tasks/compile.yml
@@ -17,7 +17,7 @@
 
 - name: Clone CLAW Alpaca
   git:
-    repo: https://github.com/Islandora-CLAW/Alpaca.git
+    repo: https://github.com/dannylamb/Alpaca.git
     dest: "{{ alpaca_clone_directory }}"
     version: "{{ alpaca_version }}"
   register: alpaca_git
diff --git a/roles/internal/crayfish/defaults/main.yml b/roles/internal/crayfish/defaults/main.yml
index 2cf93e0..fd3df83 100644
--- a/roles/internal/crayfish/defaults/main.yml
+++ b/roles/internal/crayfish/defaults/main.yml
@@ -1,5 +1,5 @@
 crayfish_user: www-data
-crayfish_version_tag: 0.0.7
+crayfish_version_tag: issue-640
 
 crayfish_services:
   - Gemini
diff --git a/roles/internal/crayfish/tasks/install.yml b/roles/internal/crayfish/tasks/install.yml
index 780e718..36f1ecc 100644
--- a/roles/internal/crayfish/tasks/install.yml
+++ b/roles/internal/crayfish/tasks/install.yml
@@ -14,7 +14,7 @@
 
 - name: Install crayfish code
   git:
-    repo: https://github.com/Islandora-CLAW/Crayfish.git
+    repo: https://github.com/dannylamb/Crayfish.git
     dest: "/var/www/html/Crayfish"
     version: "{{ crayfish_version_tag }}"
 

```

Then we need to pull in Islandora and from my branches as well, since they're not available from composer yet either.  Put the following into a file named `issue-640.sh` and run it with `$ sudo bash issue-640.sh`

```bash
cd /var/www/html/drupal/web/
/var/www/html/drupal/vendor/bin/drush --y pmu islandora_image
/var/www/html/drupal/vendor/bin/drush --y pmu islandora_collection
/var/www/html/drupal/vendor/bin/drupal config:delete active field.field.media.tn.field_mimetype
/var/www/html/drupal/vendor/bin/drupal config:delete active field.field.media.tn.field_height
/var/www/html/drupal/vendor/bin/drupal config:delete active field.field.media.tn.field_width
/var/www/html/drupal/vendor/bin/drupal config:delete active field.field.media.tn.field_image
/var/www/html/drupal/vendor/bin/drush --y pmu islandora
cd /var/www/html/drupal/web/modules/contrib/islandora
git remote add danny https://github.com/dannylamb/islandora.git
git fetch danny
git checkout issue-640
cd /var/www/html/drupal/web/modules/contrib/islandora_image
git remote add danny https://github.com/dannylamb/islandora_image.git
git fetch danny
git checkout issue-640
cd /var/www/html/drupal/web/
/var/www/html/drupal/vendor/bin/drush en -y islandora_image
```

To verify it's all working, try creating, updating, and deleting both media and nodes in Drupal.  Files won't delete until cron runs a specified time after no media/nodes reference them anymore.  So to trick drupal into using a short timeframe, run the following command from Drupal's `web` directory:

```bash
ubuntu@claw:/var/www/html/drupal/web$ drupal config:override system.file temporary_maximum_age 1
 Configuration name system.file
 ----------------------- ---------------- ---------------- 
  Configuration key       Original Value   Override Value  
 ----------------------- ---------------- ---------------- 
  temporary_maximum_age   21600            1               
 ----------------------- ---------------- ---------------- 

```

Now you can delete references to files and run cron to delete the files from Fedora.

### CODE REVIEW

**Comment by Natkeeran** [comment]
@dannylamb @whikloj 
The instructions are bit out of date.  I manually changed some and test this.  When creating the event, it gets posted to the right queue (islandora-indexing-fcrepo-content) and is picked up Alpaca as well.  But, fails to connect to Milliner.

I am getting the following error in the Karaf log:
```
2017-11-14 21:11:56,122 | ERROR | -fcrepo-content] | FcrepoIndexer                    | 166 - ca.islandora.alpaca.islandora-indexing-fcrepo - 0.3.1.SNAPSHOT | Error indexing resource in fcrepo: HTTP operation failed invoking http://localhost:8000/milliner/content with statusCode: 500

org.apache.camel.http.common.HttpOperationFailedException: HTTP operation failed invoking http://localhost:8000/milliner/content with statusCode: 500
	at org.apache.camel.component.http4.HttpProducer.populateHttpOperationFailedException(HttpProducer.java:312)
	at org.apache.camel.component.http4.HttpProducer.process(HttpProducer.java:207)
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)
	at org.apache.camel.processor.SendDynamicProcessor$1.doInAsyncProducer(SendDynamicProcessor.java:124)
	at org.apache.camel.impl.ProducerCache.doInAsyncProducer(ProducerCache.java:436)
	at org.apache.camel.processor.SendDynamicProcessor.process(SendDynamicProcessor.java:119)
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77)
```

I have the required branch for the Crayfish.
```
commit 41add9b5d450f0e28d012c9479bc350428460ea7
Author: dannylamb <dlamb@islandora.ca>
Date:   Fri Oct 20 17:59:17 2017 +0000
```

Also, noted the following:
```
fcrepo-api-x-indexing                   | 0.3.0.SNAPSHOT   |          | Uninstalled | fcrepo-api-x-karaf             | fcrepo-api-x-indexing
fcrepo-api-x-karaf                      | 0.3.0.SNAPSHOT   |          | Uninstalled | fcrepo-api-x-karaf             | fcrepo-api-x-karaf
```

**Comment by dannylamb** [comment]
@Natkeeran If you still have the box, do you see anything in the Milliner logs?

**Comment by Natkeeran** [comment]
@dannylamb Milliner log does not get created.

**Comment by dannylamb** [comment]
@Natkeeran Sounds like a permissions issue 😦

**Comment by Natkeeran** [comment]
@dannylamb 
### apache error log:
```
[Wed Nov 15 15:59:53.665632 2017] [:error] [pid 5665] [client 127.0.0.1:46684] PHP Fatal error:  Uncaught Pimple\\Exception\\UnknownIdentifierException: Identifier "crayfish.debug" is not defined. in /var/www/html/Crayfish/Milliner/vendor/pimple/pimple/src/Pimple/Container.php:101\nStack trace:\n#0 /var/www/html/Crayfish/Milliner/src/app.php(19): Pimple\\Container->offsetGet('crayfish.debug')\n#1 /var/www/html/Crayfish/Milliner/src/index.php(3): require_once('/var/www/html/C...')\n#2 {main}\n  thrown in /var/www/html/Crayfish/Milliner/vendor/pimple/pimple/src/Pimple/Container.php on line 101

```
I commented out line [19](https://github.com/Islandora-CLAW/Crayfish/blob/41add9b5d450f0e28d012c9479bc350428460ea7/Milliner/src/app.php#L19) and now Milliner log gets generated.  It has the following error:

### milliner error log
```
[2017-11-15 11:07:37] app.CRITICAL: Pimple\Exception\UnknownIdentifierException: Identifier "crayfish.gemini_base_url" is not defined. (uncaught exception) at /var/www/html/Crayfish/Milliner/vendor/pimple/pimple/src/Pimple/Container.php line 101 {"exception":"[object] (Pimple\\Exception\\UnknownIdentifierException(code: 0): Identifier \"crayfish.gemini_base_url\" is not defined. at /var/www/html/Crayfish/Milliner/vendor/pimple/pimple/src/Pimple/Container.php:101)"} []
[2017-11-15 11:07:37] app.DEBUG: < 500 [] []
```

**Comment by dannylamb** [comment]
@Natkeeran Ah ok. It's a config deployment issue. I must've missed committing them after working out the issues :man_facepalming:

**Comment by Natkeeran** [comment]
@dannylamb It is more likely that I did not follow the instructions properly.  Sorry if I lead you astray.  @whikloj game me some guidance, and I am testing it again.

**Comment by Natkeeran** [comment]
@dannylamb @whikloj The above noted issues are due to me not following the instructions clearly.  I am able to build the machine following the instructions.  When a node gets created, it gets synched to fedora.  However, when trying to create media from inline forms (i.e image), I am seeing the following error:
```
Drupal\Core\Entity\EntityStorageException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '1) VALUES ('15', NULL, '016d6b8a79c713e3bfc2a0e4c5c3afcaa98a9476', NULL, '')' at line 1: INSERT INTO {filehash} (fid, md5, sha1, sha256, 1) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4); Array ( [:db_insert_placeholder_0] => 15 [:db_insert_placeholder_1] => [:db_insert_placeholder_2] => 016d6b8a79c713e3bfc2a0e4c5c3afcaa98a9476 [:db_insert_placeholder_3] => [:db_insert_placeholder_4] => ) in Drupal\Core\Entity\Sql\SqlContentEntityStorage->save() (line 805 of /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php).
```

**Comment by MarcusBarnes** [comment]
Confirming that I'm seeing the same behaviour as @Natkeeran.

**Comment by whikloj** [comment]
I think I got it, the claw_vagrant script you run once your vagrant is up is different. It installs filehash, this one doesn't seem to.

@Natkeeran @MarcusBarnes - If you can try this again but instead of putting the stuff listed above into the `issue-640.sh` script, use this [gist](https://gist.githubusercontent.com/dannylamb/9bf360d63e8c4a829ff72b75faba2264/raw/6020d83dc514748a9df9ade26c6790cebff3b47f/issue-640.sh) once vagrant is up.

I'm going to try this tomorrow too.

**Comment by MarcusBarnes** [comment]
We got the following error when running the gist:
``
> DrupalProject\composer\ScriptHandler::createRequiredFiles
filehash is already enabled.                                                                                  [ok]
There were no extensions that could be enabled.                                                               [ok]
The source directory does not exist.                                                                          [error]
``

The following appear in the Drupal log when trying to add an image to a basic image:

``
Drupal\Core\Entity\EntityStorageException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '1) VALUES ('3', NULL, '016d6b8a79c713e3bfc2a0e4c5c3afcaa98a9476', NULL, '')' at line 1: INSERT INTO {filehash} (fid, md5, sha1, sha256, 1) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4); Array ( [:db_insert_placeholder_0] => 3 [:db_insert_placeholder_1] => [:db_insert_placeholder_2] => 016d6b8a79c713e3bfc2a0e4c5c3afcaa98a9476 [:db_insert_placeholder_3] => [:db_insert_placeholder_4] => ) in Drupal\Core\Entity\Sql\SqlContentEntityStorage->save() (line 805 of /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php).
``


``
Drupal\Core\Database\DatabaseExceptionWrapper: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '1) VALUES ('3', NULL, '016d6b8a79c713e3bfc2a0e4c5c3afcaa98a9476', NULL, '')' at line 1: INSERT INTO {filehash} (fid, md5, sha1, sha256, 1) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4); Array ( [:db_insert_placeholder_0] => 3 [:db_insert_placeholder_1] => [:db_insert_placeholder_2] => 016d6b8a79c713e3bfc2a0e4c5c3afcaa98a9476 [:db_insert_placeholder_3] => [:db_insert_placeholder_4] => ) in filehash_save() (line 192 of /var/www/html/drupal/web/modules/contrib/filehash/filehash.module).
``


``
Warning: hash_file(): Unknown hashing algorithm: 1 in filehash_hash() (line 130 of /var/www/html/drupal/web/modules/contrib/filehash/filehash.module) #0 /var/www/html/drupal/web/core/includes/bootstrap.inc(566): _drupal_error_handler_real(2, 'hash_file(): Un...', '/var/www/html/d...', 130, Array) #1 [internal function]: _drupal_error_handler(2, 'hash_file(): Un...', '/var/www/html/d...', 130, Array) #2 /var/www/html/drupal/web/modules/contrib/filehash/filehash.module(130): hash_file('1', 'public://media-...') #3 /var/www/html/drupal/web/modules/contrib/filehash/filehash.module(25): filehash_hash(Object(Drupal\file\Entity\File)) #4 [internal function]: filehash_file_create(Object(Drupal\file\Entity\File)) #5 /var/www/html/drupal/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(402): call_user_func_array('filehash_file_c...', Array) #6 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(167): Drupal\Core\Extension\ModuleHandler->invokeAll('file_create', Array) #7 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/ContentEntityStorageBase.php(435): Drupal\Core\Entity\EntityStorageBase->invokeHook('create', Object(Drupal\file\Entity\File)) #8 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(191): Drupal\Core\Entity\ContentEntityStorageBase->invokeHook('create', Object(Drupal\file\Entity\File)) #9 /var/www/html/drupal/web/modules/contrib/media_entity/src/Entity/Media.php(226): Drupal\Core\Entity\EntityStorageBase->create(Array) #10 /var/www/html/drupal/web/modules/contrib/media_entity/src/Form/MediaInlineForm.php(49): Drupal\media_entity\Entity\Media->automaticallySetThumbnail() #11 /var/www/html/drupal/web/modules/contrib/inline_entity_form/src/Element/InlineEntityForm.php(155): Drupal\media_entity\Form\MediaInlineForm->entityFormSubmit(Array, Object(Drupal\Core\Form\FormState)) #12 [internal function]: Drupal\inline_entity_form\Element\InlineEntityForm::submitEntityForm(Array, Object(Drupal\Core\Form\FormState)) #13 /var/www/html/drupal/web/modules/contrib/inline_entity_form/src/ElementSubmit.php(109): call_user_func_array(Array, Array) #14 /var/www/html/drupal/web/modules/contrib/inline_entity_form/src/ElementSubmit.php(102): Drupal\inline_entity_form\ElementSubmit::doSubmit(Array, Object(Drupal\Core\Form\FormState)) #15 /var/www/html/drupal/web/modules/contrib/inline_entity_form/src/ElementSubmit.php(102): Drupal\inline_entity_form\ElementSubmit::doSubmit(Array, Object(Drupal\Core\Form\FormState)) #16 /var/www/html/drupal/web/modules/contrib/inline_entity_form/src/ElementSubmit.php(102): Drupal\inline_entity_form\ElementSubmit::doSubmit(Array, Object(Drupal\Core\Form\FormState)) #17 /var/www/html/drupal/web/modules/contrib/inline_entity_form/src/ElementSubmit.php(102): Drupal\inline_entity_form\ElementSubmit::doSubmit(Array, Object(Drupal\Core\Form\FormState)) #18 /var/www/html/drupal/web/modules/contrib/inline_entity_form/src/ElementSubmit.php(79): Drupal\inline_entity_form\ElementSubmit::doSubmit(Array, Object(Drupal\Core\Form\FormState)) #19 [internal function]: Drupal\inline_entity_form\ElementSubmit::trigger(Array, Object(Drupal\Core\Form\FormState)) #20 /var/www/html/drupal/web/core/lib/Drupal/Core/Form/FormSubmitter.php(111): call_user_func_array(Array, Array) #21 /var/www/html/drupal/web/core/lib/Drupal/Core/Form/FormSubmitter.php(51): Drupal\Core\Form\FormSubmitter->executeSubmitHandlers(Array, Object(Drupal\Core\Form\FormState)) #22 /var/www/html/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(585): Drupal\Core\Form\FormSubmitter->doSubmitForm(Array, Object(Drupal\Core\Form\FormState)) #23 /var/www/html/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(314): Drupal\Core\Form\FormBuilder->processForm('node_islandora_...', Array, Object(Drupal\Core\Form\FormState)) #24 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityFormBuilder.php(48): Drupal\Core\Form\FormBuilder->buildForm('node_islandora_...', Object(Drupal\Core\Form\FormState)) #25 /var/www/html/drupal/web/core/modules/node/src/Controller/NodeController.php(113): Drupal\Core\Entity\EntityFormBuilder->getForm(Object(Drupal\node\Entity\Node)) #26 [internal function]: Drupal\node\Controller\NodeController->add(Object(Drupal\node\Entity\NodeType)) #27 /var/www/html/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array) #28 /var/www/html/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(576): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #29 /var/www/html/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #30 /var/www/html/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) #31 [internal function]: Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #32 /var/www/html/drupal/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Object(Closure), Array) #33 /var/www/html/drupal/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #34 /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #35 /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #36 /var/www/html/drupal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(99): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #37 /var/www/html/drupal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(78): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true) #38 /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #39 /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(50): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #40 /var/www/html/drupal/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #41 /var/www/html/drupal/web/core/lib/Drupal/Core/DrupalKernel.php(657): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #42 /var/www/html/drupal/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #43 {main}.
``

I hope the above are relevant and helpful.  Thanks in advance.

**Comment by whikloj** [comment]
Hmm okay. I'm wrong about filehash, it is already added in the patch above...this worked so well in vagrant. I'll try rebuilding this again as described above and see if I can catch anything the second time around.

**Comment by MarcusBarnes** [comment]
@whikloj  When testing, please be sure to create a basic image object and attach an image (say, a .tiff file) to see if you get similar messages in the Drupal log.

**Comment by whikloj** [comment]
Ok so I feel like filehash is the problem. In my claw-playbook the filehash.view.inc was throwing errors, but in claw_vagrant it was fine. I just built another claw_vagrant box and it works great. I'm going to try building this again tomorrow expect I won't install filehash at the start and will mimic the claw_vagrant process of installing it at the end.

**Comment by dannylamb** [comment]
@whikloj @Natkeeran @MarcusBarnes hopping onto this as well.  let me see what pops.

Looks like being clever and providing a patch has failed since the code has shifted underneath :man_facepalming:

**Comment by whikloj** [comment]
I have been using your (@dannylamb) issue-640 claw-playbook branch to build this so I don't think it has changed. I am using this branch but have removed the filehash lines so it isn't installed and I have commented out the installation of the drupal configuration (much like claw_vagrant). 

I'm going to reinstall it after words in much the same way as claw_vagrant. I'll let you all know what happens.

**Comment by dannylamb** [comment]
@whikloj oh, ha, i was on master....  no wonder the patch wasn't applying.  let's try that again...

**Comment by whikloj** [comment]
Could all this be due to the difference in MySQL version between vagrant and playbook? Everything seems to have loaded and installed correctly. Its just that INSERT statement that throws a MySQL Exception.

**Comment by whikloj** [comment]
Or maybe MySQL configuration options? 
https://github.com/bennojoy/mysql/blob/master/defaults/main.yml#L25

**Comment by dannylamb** [comment]
@whikloj @Natkeeran @MarcusBarnes So it appears that even though we've got the config loaded up, it's just not taking hold correctly in Drupal.  For example, in the filehash settings, we've got `dedupe: true`, but if you go to the actual config form, that checkbox is empty instead of checked.  Oddly enough, if you go to the configuration synchronization dashboard and export filehash.settings, it is what ansible provies and even has `dedupe: true` in it!  The Node and Media REST endpoints also behave similarly.

My best guess is something's up with how I'm deploying the configs through Ansible.  That or it's an 8.4 issue.

**Comment by whikloj** [comment]
@dannylamb oh...here I was so excited that I figured it out and you already had.
The config we are loading is taking `dedupe: true` as an algorithm and that causes the problem. If you go **Admin** -> **Configuration** -> **Media** -> **Filehash**, change a setting and save, change it back. Then it works perfectly.

**Comment by whikloj** [comment]
Also when I pull this branch and look at the `filehash.settings.yml` in the `roles/internal/webserver-app/files` directory. I see

```
lgos:
  sha1: sha1
  md5: '0'
  sha256: '0'
  dedupe: true
```

**Comment by whikloj** [comment]
https://github.com/dannylamb/claw-playbook/compare/issue-640...whikloj:weird-spaces?expand=1

**Comment by whikloj** [comment]
Confirmed, fixing the `filehash.settings.yml` in this PR I was able to stand up the playbook following these instructions exactly and create a Collection and an Image with file that were all persisted to Fedora. Able to edit and delete and see that occur in Fedora. 

For some reason the JPG I uploaded to Drupal is still listed as Permanent even after deleting the Media associated with it, but I'll see if that changes shortly.

**Comment by Natkeeran** [comment]
@whikloj @dannylamb We are close.  

After getting @whikloj change, able to create/delete media.  Some media info such as title does not populated in Fedora even thought is specified in RDF mapping for that bundle.  I applied the maximum_age command and ran the cron, but the entries do not get deleted in Fedora.

**Comment by whikloj** [comment]
Is the entry (I'm assuming a file) deleted from Drupal?

**Comment by whikloj** [comment]
@Natkeeran Sorry I missed the last sentence of your comment. I did notice the same issue for a JPG I uploaded. The fact the the file is not delete from Drupal is why it does not delete from Fedora. But I am unclear why the file gets a status of Permanent and is never removed from Drupal.

**Comment by Natkeeran** [comment]
@whikloj yes, that is correct.  Files are marked permanent and are not deleted from Drupal.  

My understanding is that Media bundles get synched to Fedora as well.  Thus, If we create a Media entry there should be a corresponding Fedora entry.  The current corresponding entry does not reflect the mapping.

(Note that Media did not have REST configured by default. It should.  But, configuring it still does not solve the issue.)

```
uuid: 0a1369ba-3052-4194-801d-b32f96cb99cb
langcode: en
status: true
dependencies:
  config:
    - media_entity.bundle.web_content
  enforced:
    module:
      - islandora_image
  module:
    - media_entity
_core:
  default_config_hash: iDbQbJblaZWIoXCEPfb_aePaQP7eW6SlK5M_Vvxe98g
id: media.web_content
targetEntityType: media
bundle: web_content
types:
  - 'use:ServiceFile'
fieldMappings:
  name:
    properties:
      - 'dc:title'
      - 'rdf:label'
  created:
    properties:
      - 'schema:dateCreated'
    datatype_callback:
      callable: 'Drupal\rdf\CommonDataConverter::dateIso8601Value'
  changed:
    properties:
      - 'schema:dateModified'
    datatype_callback:
      callable: 'Drupal\rdf\CommonDataConverter::dateIso8601Value'
  uid:
    properties:
      - 'schema:author'
    mapping_type: rel
  field_mimetype:
    properties:
      - 'ebucore:hasMimeType'
```

**Comment by whikloj** [comment]
I don't think the Media bundles are persisted to Fedora, but I could be incorrect. Have to bring @dannylamb in for confirmation.

**Comment by dannylamb** [comment]
@whikloj Oh man, what a facepalm...  Ok, so the REST entities are also suffering from that as well.  I'll re-export and we'll try this again.

**Comment by dannylamb** [comment]
Second facepalm... refresh the browser instead of looking at an old tab.

@Natkeeran @whikloj Media _should_ be persisted as the LDP-RS that describes the LDP-NR.  The changes associated wtih Islandora-CLAW/CLAW#640 actually implement that.  The codebase as it stands does not persist media at all.

The weird bit, because of how Drupal handles the whole file reference thing, is that deleting Media _does not_ delete its counterpart in Fedora, as that would trigger the deletion of the LDP-NR but keep the File dangling in Drupal.  To make matters worse, in Drupal 8.4, they've disabled the deletion of files when there's no more references.  This means we'll have to start deleting Files in response to Media getting deleted, which, in all honesty, sounds like a better approach anyway.

**Comment by dannylamb** [comment]
@whikloj @Natkeeran I just pushed fixes to the configuration.  I `vagrant up`'d with it and followed the testing instructions and everything worked fine.  Media sync'd its metadata just fine.  I could confirm because the filename flows through as dc:title.

Since this is on 8.4, files will _not_ delete as per the testing instructions due to changes that were made.  That's my bad because I wrote the changes targeting 8.3 and didn't realize claw-playbook wasn't locked down to a particular version of Drupal.  For the sake of getting these changes in, let's handle deleting files when deleting media in a separate ticket if possible.

**Comment by whikloj** [comment]
`vagrant up`

**Comment by whikloj** [comment]
Ok this works. But I don't see any of the alternative text from the media. What I get for one islandora_collection is one RDFSource object. For one islandora_image with a Web Image and a TN. I get 3 resources, 1 RDFSource and 2 NonRDFSource. The NonRDFSource do not contain the alternative text.

Maybe that is for another day.

Also the correction to the resource entity needs to happen in the actual islandora module.
https://github.com/Islandora-CLAW/islandora/blob/8.x-1.x/config/install/rest.resource.entity.media.yml#L12-L14

**Comment by dannylamb** [comment]
@whikloj I'm not sure if/how we can map the alternative text.  I'm guessing as long as its either a field or a property we're ok.

https://github.com/Islandora-CLAW/islandora/pull/67/files actually pulls the file altogether since we install with both claw_vagrant and claw-playbook.  I'll do a README update to say you need to manually configure it if you're installing it on your own.

**Comment by whikloj** [comment]
@Natkeeran you want to try this and let me know if you are satisfied.

**Comment by Natkeeran** [comment]
@whikloj sure, get the latest from the branch and vagrant up.  Is that right?

**Comment by whikloj** [comment]
@Natkeeran yep, you still need to apply the patch and run the batch script inside the vagrant machine. But otherwise it should work out of the box.

**Pull request merged**
