### PR TITLE
change islandora_demo to islandora_defaults

### PR DESCRIPTION
**Pull request by Natkeeran**
**GitHub Issue**:  https://github.com/Islandora-CLAW/CLAW/issues/970

## What does this Pull Request do?
* Implements the name change of the islandora_demo to islandora_defaults in playbook.

## How should this be tested?
* Get the PR
* Vagrant up
* Sanity checks

@Islandora-Devops/committers

### CODE REVIEW

**Comment by whikloj** [comment]
👀

**Comment by whikloj** [comment]
@Natkeeran not actually related to this PR, but could you bump the `ansible-role-crayfish` version from `0.3.0` to `0.3.1` to pick up @dannylamb's latest changes in Crayfish. Then I can test it all.

**Comment by dannylamb** [comment]
I found some bugs with that code and I'm working on it.  More subtle interplay with file uris for media subjects...  Was going to make a ticket, but was going to wait until I had a PR to pull everything in.

**Comment by dannylamb** [comment]
FYI https://github.com/Islandora-CLAW/islandora/pull/139

Those bugs proved to be too much for too short of a time but `0.3.1` should work out just fine without the form.

**Comment by dannylamb** [comment]
`vagrant up` with `0.3.1` for the crayfish role.  This is basically it for the release!

**Comment by dannylamb** [comment]
With `0.3.1` this passed my sanity checks.  Fedora indexing is working. Derivatives are working.  Viewers are working.  Triplestore is indexing from both Drupal and Fedora.

:shipit:

**Pull request merged**
