### PR TITLE
Mark failure ok when checking symfony/flex version.

### PR DESCRIPTION
**Pull request by rosiel**
# What does this Pull Request do?

Big red error is scary. This lets you know it's ok.

# Interested parties
@alxp

### CODE REVIEW

**Comment by whikloj** [comment]
Is this section still required now that the whole of Crayfish is using Symfony?

**Comment by rosiel** [comment]
😅 I'll try taking it out. Can you help test?

**Comment by whikloj** [comment]
I can, but I'll also ask @alxp to confirm what the behavior he was experiencing originally, 'cause I think he added this.

**Comment by rosiel** [comment]
Already done (i.e. the whole section remove) by @whikloj . Thanks!

**Pull request closed without merging**
