### PR TITLE
Enable profiling in Ansible

### PR DESCRIPTION
**Pull request by jonathangreen**
This PR adds a line to the Ansible config to enable profiling. Gives some interesting data that might help us reduce the time it takes to start things up eventually. 

Gives a nice summary like this after the playbook is run:
```
Thursday 21 September 2017  10:56:35 -0300 (0:00:02.065)       0:20:59.319 **** 
=============================================================================== 
drupal : Install dependencies with composer require. ------------------ 196.72s
drupal : Generate Drupal project with composer package. --------------- 161.62s
grok : Make grok ------------------------------------------------------- 98.60s
alpaca : Add Alpaca Features ------------------------------------------- 98.56s
php : Ensure PHP packages are installed. ------------------------------- 55.50s
apix : Add API-X Features ---------------------------------------------- 37.45s
java : Ensure Java is installed. --------------------------------------- 37.43s
crayfish : Build crayfish code including dependencies ------------------ 36.29s
install extra packages ------------------------------------------------- 24.92s
tomcat8 : install tomcat8 ---------------------------------------------- 24.34s
mysql : Ensure MySQL packages are installed. --------------------------- 22.25s
solr : Download Solr. -------------------------------------------------- 20.06s
openseadragon : Install Openseadragon with composer -------------------- 19.71s
tomcat8 : tomcat8 restart tomcat8 -------------------------------------- 18.90s
crayfish : Install requisite packages ---------------------------------- 16.94s
drupal : Install Drupal with drush. ------------------------------------ 15.49s
solr : Run Solr installation script. ----------------------------------- 14.85s
install aptitude ------------------------------------------------------- 13.81s
drupal : Install configured modules with drush. ------------------------ 13.14s
blazegraph : Download blazegraph war ----------------------------------- 12.66s
```

### CODE REVIEW

**Comment by DiegoPino** [comment]
@jonathangreen great! There are some nice callback profiles around! **https://github.com/ansible/ansible/tree/devel/lib/ansible/plugins/callback**
Does this adds any version restriction to ansible we could need to document?

**Comment by DiegoPino** [comment]
Answering to myself, seems like since 2.0 it is part of the release. Will merge

**Comment by DiegoPino** [comment]
@dannylamb does the 24hr limit apply here? i guess not

**Comment by ajs6f** [comment]
Wow, this is super cool, @jonathangreen !

**Comment by dannylamb** [comment]
@jonathangreen++

@DiegoPino You are correct, the 24h limit does not apply here.  We're on the honor system still.  Only if someone messes that up will I have to enforce the types of restrictions we have in 7.x.

**Pull request merged**
